### ISSUE TITLE
Allow multiple plans downloads

### ISSUE THREAD

**Issue by mvazquezc** [karmab/kcli#100]
I would like to download multiple plans using kcli plan --get

e.g: kcli plan --get github.com/karmab/kcli/plans/ -p ~/kcli_plans/

The expected output will be all plans located on that repo being downloaded to ~/kcli_plans/

**Comment by karmab** [comment]
congrats on issue number 100 @mvazquezc

**Comment by karmab** [comment]
products addressed this a better way, you can just do
kcli repo -u https://github.com/karmab/kcli-plans karmab
and then the repo wil be (git) clone at ~/.kcli/plans/karmab

then you can either:
- launch plans manually from this repo
- provided the repo has a properly defined KMETA , use kcli list --products and kcli product XXX
