### ISSUE TITLE
[RFE] Do not overwrite .ssh/authorized_keys on ovirt

### ISSUE THREAD

**Issue by iranzo** [karmab/kcli#113]
On templates predefined with user ssh keys kcli overwrites ".ssh/authorized_keys" and leaves users locked out.

**Comment by karmab** [comment]
the issue seems to be specific to ovirt and despitethe change done in https://github.com/karmab/kcli/commit/ed78da542467dc5900573d43da736d6a2dc6e1d4
so it seems to be an ovirt sdk specific bug

**Comment by iranzo** [comment]
Upstream bug open at <https://bugzilla.redhat.com/show_bug.cgi?id=1635844>

I would rather flag this as 'depends-on-others' to revisit in the future

**Comment by karmab** [comment]
the upstream bug was solved, but sadly it doesn't address our concern.
regardless of the indicated option or any other, the keys get overriden
i m closing this since one can indicate a list of keys, not just a single one,  on kcli side
