### ISSUE TITLE
[RFE] Manage snapshots from plan level

### ISSUE THREAD

**Issue by soukron** [karmab/kcli#138]
As a user I'd like to manage the snapshot of all vms of a plan:

- Take a snapshot:
 $ kcli plan --snapshot myplan freshOSInstall
- Delete a snapshot
 $ kcli plan --snapshot myplan -d freshOSInstall
- Revert to a snapshot
 $ kcli plan --snapshot myplan -r freshOSInstall

It's okay if any of the underlying snapshot actions fails and needs to be fixed individually.

**Comment by karmab** [comment]
addressed in several commits
