### ISSUE TITLE
Add macvtap support

### ISSUE THREAD

**Issue by sp3t3rs** [karmab/kcli#139]
Hey everbody,

as @NerdsvilleCEO mentioned in #81, there is no support for using host devices (e.g through macvtap) in the `nets` section. This would be a really nice feature.

@karmab - I saw your talk at FOSDEM 2019. kcli is awesome, love it!

Cheers

**Comment by karmab** [comment]
thanks for the feedback!
let me have a look about adding macvtap support

**Comment by cburkins** [comment]
New to KVM/libvert, simply setting up a home server as a hypervisor machine to run a bunch of VM's insdie my house.   Was creating the VM's by hand (via virt-manager) until I found kcli, very good stuff, nicely done !   When creating by hand, I think macvtap is the only way to easily provide a public IP for each VM (IP is given out by my router/DHCPServer).   I guess I could create the machines via kcli, then update the networking via virt-manager to be macvtap ?

**Comment by karmab** [comment]
technically, the way i give vms a "public" ip is simply by 
- setting a bridge on top of the default interface of your hypervisor (in my case, it's generally a wired connection).
- using this network in kcli (which will be reported in `kcli list network`)

In this configuration, qemu-guest-agent will actually take care of reporting the ip used by the vm, so you can still `kcli ssh` to it

**Comment by cburkins** [comment]
Hmmm, OK, I'll have to read up on that a bit.   Saw reference to that
concept, but then found the shortcut of setting network to "macvtap" within
virt-manager.   Will try to get that setup.

**Comment by karmab** [comment]
to give it a try, i've added some preliminary support for macvtap in https://github.com/karmab/kcli/commit/3c9c7b1f510c4ff9acc45ecdb87c9201eb7c3d3b

my understanding is that you only to create a macvtap network in libvirt on top of a specified nic, and then use it as a regular network.
so latest commit adds the ability to create a macvtap network with the following invocation

```
kcli create network -P macvtap=true -P nic=eth0 my_net
```

you can then use this network when creating a vm, for instance, with a oneliner like

```
kcli create vm -i centos7 -P nets=[my_net]
```

i havent fully tested it (but i will) and will think how to improve end user experience for this case.

**Comment by karmab** [comment]
ran a test and seems to work as expected :)

**Comment by cburkins** [comment]
That’s great !  Thx for the consideration, looking forward to it.

**Comment by cburkins** [comment]
> technically, the way i give vms a "public" ip is simply by
> 
> * setting a bridge on top of the default interface of your hypervisor (in my case, it's generally a wired connection).
> * using this network in kcli (which will be reported in `kcli list network`)
> 
> In this configuration, qemu-guest-agent will actually take care of reporting the ip used by the vm, so you can still `kcli ssh` to it

Just to verify, are you created the bridge network using OS tools (e.g. netplan on Ubuntu), or are you using virt-manager to create the bridge network.   I seem to be having modest success with both, but nothing entirely successful yet.  Creating the network (e.g. br0) via virt-manager feels the most straight-forward; however, so far, I can only send traffic outbound from the VM, haven't been able to access the VM from another machine in my home network.   The virt-manager bridge is set for "NAT" Forwarding, which seems to align with that.   "Routed" forwarding seems to imply that I need to setup a route on my home router ?

**Comment by sp3t3rs** [comment]
Thanks for the first macvtap shot in [3c9c7b1](https://github.com/karmab/kcli/commit/3c9c7b1f510c4ff9acc45ecdb87c9201eb7c3d3b)! 

> technically, the way i give vms a "public" ip is simply by
>     * setting a bridge on top of the default interface of your hypervisor (in my case, it's generally a wired connection).
>     * using this network in kcli (which will be reported in `kcli list network`)

Funny coincidence: this setup would've solved my original problem from last year as well. However, macvtap has some advantages over bridges in some use-cases so it's nice to see it supported by kcli!

**Comment by karmab** [comment]
> > technically, the way i give vms a "public" ip is simply by
> > 
> > * setting a bridge on top of the default interface of your hypervisor (in my case, it's generally a wired connection).
> > * using this network in kcli (which will be reported in `kcli list network`)
> > 
> > In this configuration, qemu-guest-agent will actually take care of reporting the ip used by the vm, so you can still `kcli ssh` to it
> 
> Just to verify, are you created the bridge network using OS tools (e.g. netplan on Ubuntu), or are you using virt-manager to create the bridge network. I seem to be having modest success with both, but nothing entirely successful yet. Creating the network (e.g. br0) via virt-manager feels the most straight-forward; however, so far, I can only send traffic outbound from the VM, haven't been able to access the VM from another machine in my home network. The virt-manager bridge is set for "NAT" Forwarding, which seems to align with that. "Routed" forwarding seems to imply that I need to setup a route on my home router ?

I create such a bridge using nmcli or a proper ifcfg file, i mean it's not a libvirt type bridge. It's a regular bridge
for instance, with nmcli (and supposing your default interface is eth0 and uses dhcp) (use with caution!!!)

```
export MAIN_CONN=eth0
sudo nmcli connection add ifname localnet type bridge con-name localnet
sudo nmcli con add type bridge-slave ifname "$MAIN_CONN" master localnet
sudo nmcli con down "System $MAIN_CONN"; sudo pkill dhclient; sudo dhclient localnet
```

**Comment by karmab** [comment]
i think this issue can be closed, since macvtap has been added.
for information regarding how to set the bridge, feel free to ping me on slack #kcli under kubernetes workspace ;)
