### ISSUE TITLE
RFE: be able to redeploy plans when a single host is changed

### ISSUE THREAD

**Issue by efenex** [karmab/kcli#14]
Currently, redeploying an existing plan causes exceptions on already existing volumes/machines. As I'm currently redeploying frequently, it's faster to do it partially rather than redeploy the full stack.

I patched this by catching some libvirtErrors in the create() function for storagepool.createXML() and conn.defineXML(), and returning failure when they occur (which still lets the plan go through); if you want I can provide the diff/PR, but I imagine there is a cleaner solution.

**Comment by efenex** [comment]
oh, one unexpected consequence is that my `kcli list` only lists the IP for the host that was redeployed, it seems old ones disappear - so definitely not a good solution.

**Comment by karmab** [comment]
i ve changed the code so that existing vms are skipped when deploying a plan ( with a blue warning about it)

**Comment by efenex** [comment]
great, thanks a lot!
