### ISSUE TITLE
[RHV]  kcli list --images tries to launch ssh

### ISSUE THREAD

**Issue by iranzo** [karmab/kcli#143]
When trying to list images against a RHV host, an attempt to reach to it via ssh is made:

~~~sh
kcli list --images
Listing images...
ssh: Could not resolve hostname citellus.org : Name does not resolve
+------+
| Name |
+------+
+------+
~~~

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/59963c360ae2fce7395e71c6487175da3e48bc3c
