### ISSUE TITLE
Confusing message "Plan XXXXX started!" even when the plan does not exist. 

### ISSUE THREAD

**Issue by jtudelag** [karmab/kcli#148]
Plan XXXX does not exist, but kcli shows a message saying the plan has been started....

```
$ kcli plan -s XXXXX
Starting vms from plan XXXXX
Plan XXXXX started!
```

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/4c4c2ec762b336e7fbcd09c0a4c49590dbd45158
