### ISSUE TITLE
bootstrap crashes

### ISSUE THREAD

**Issue by duck-rh** [karmab/kcli#15]
> $ kcli bootstrap
> Using local hypervisor as no kcli.yml was found...
> Bootstrapping env
> We will configure kcli together !
> Enter your default client name[local]: ex1
> Enter your default pool[default]: 
> Enter your client first disk size[10]: 
> Enter your client first network[default]: 
> Use cloudinit[True]: 
> Use thin disks[True]: 
> Enter your client hostname/ip[localhost]: 
> Enter your client url: 
> Enter your client port: 
> Enter your client user[root]: 
> Enter your client pool[default]: 
> Create pool if not there[Y]: 
> Enter yourpool path[/var/lib/libvirt/images]: 
> Enter your client first disk size[10]: 
> Enter your client first network[default]: 
> Create net if not there[Y]: 
> Enter cidr [192.168.122.0/24]: 
> Create cinet network for uci demos if not there[N]
> Use cloudinit for this client[True]: 
> Use thin disks for this client[True]: 
> Traceback (most recent call last):
>   File "/home/duck/bin/kcli", line 11, in <module>
>     sys.exit(cli())
>   File "/home/duck/.local/lib/python2.7/site-packages/click/core.py", line 716, in **call**
>     return self.main(_args, *_kwargs)
>   File "/home/duck/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/home/duck/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/duck/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "/home/duck/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(_args, **kwargs)
>   File "/home/duck/.local/lib/python2.7/site-packages/kvirt/cli.py", line 714, in bootstrap
>     k.bootstrap(pool=pool, poolpath=poolpath, pooltype=pooltype, nets=nets)
> UnboundLocalError: local variable 'pooltype' referenced before assignment

**Comment by karmab** [comment]
fixed with last commit
Note that as per your capture, you have better used 
kcli bootstrap -a
