### ISSUE TITLE
VM's should autostart

### ISSUE THREAD

**Issue by iranzo** [karmab/kcli#151]
Created VM's, using OCP4 plan are not restarted automatically on server reboot

It would be good to default to autostart vm's on restart

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/0f057a257f90b2020e55e2a87bb07b7e42070e7d
with an extra autostart parameter to use on command line when creating a vm (with -P autostart=true) or within plans.
Note that we still not autostart vms by default, to make users low on resources happy
