### ISSUE TITLE
Canonical moved/deleted some cloud-based images

### ISSUE THREAD

**Issue by jruariveiro** [karmab/kcli#152]
Sorry for trying to use these amateur images, but seems canonical decided to move/delete some of them:

for i in ubuntu1610 ubuntu1704 ubuntu1710 ubuntu1810; do kcli download $i; done

Causing kcli to fail. 
Shame on you, shuttleworth

Tested on:
Fedora release 30 (Thirty)
Kcli version 14.13

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/7354459e9e9cc3e2685dacdf8cc63d7a854e3b9c
and adding ubuntu 1904

**Comment by jruariveiro** [comment]
Thanks
