### ISSUE TITLE
RFE - Implement Net creation in Route mode instead of just NAT 

### ISSUE THREAD

**Issue by jparrill** [karmab/kcli#159]
In order to work with routed networks in remote Hosts with libvirt, Kcli should provide an easy way to create networks with forward method `nat` and `routed` instead just `nat`.

**Comment by karmab** [comment]
Addressed in https://github.com/karmab/kcli/commit/368ae5345465d63c670d5f6a0c7ff1e92b8c0b9d where we basically set forward as route when specifying isolated (but dhcp)

You can create the network with something like

```
kcli network -c 16.0.0.0/24 -i hendrix
````

or with the following snippet in a plan:

```
hendrix:
 type: network
 cidr: 16.0.0.0/24
 nat: false
```
