### ISSUE TITLE
Missing Ubuntu 19.10

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli#161]
https://github.com/karmab/kcli/blob/6ee3f50e363ae2835710ef2f498ae1a211319479/kvirt/defaults.py#L56

https://cloud-images.ubuntu.com/releases/eoan/release/ubuntu-19.10-server-cloudimg-amd64.img

**Comment by karmab** [comment]
added in https://github.com/karmab/kcli/commit/cc9fdb5dfd203f908c162dd5eff7a6707953fb78
