### ISSUE TITLE
Rhel8 + docker ce

### ISSUE THREAD

**Issue by mathgonzlez** [karmab/kcli#169]
kcli fails to communicate with docker ce, it only works with podman in RHEL 8. is there any way to replace podman with ce?

**Comment by karmab** [comment]
hello, can you provide the error you get?
regards,

**Comment by mathgonzlez** [comment]
After installing kcli it fails to connect to Docker and requires a podman. Is it the only way to use kcli?

![Screenshot from 2019-12-31 02-19-08](https://user-images.githubusercontent.com/57609433/71610937-077c2a80-2b74-11ea-9bf0-823635a66376.png)

**Comment by karmab** [comment]
hum, it looks like an issue with the install script, if you have docker installed, the aliases created for your shell should have matched this...
as a quick around, you can substitute podman by docker in your ~/.bashrc file.

**Comment by mathgonzlez** [comment]
I could solve it, the mistake was mine. I installed kcli in a new installation of rhel (by default it comes with podman) and then replace podman with docker so kcli was still looking for podman. reinstall rhel, then replace podman with docker and finally install kcli. Everything works great. Thanks!
