### ISSUE TITLE
[RFE] kcli list -p

### ISSUE THREAD

**Issue by g0trunks** [karmab/kcli#17]
Missing capability to list plans.

kcli list -p
kcli list plans

**Comment by jtudelag** [comment]
I like the feature, but whats the best approach?
**kcli list plans** or **kcli plan --list** ??

**Comment by karmab** [comment]
Will be kcli plan --list ( or-l), as all the list code will be moved to the
relevant section

**Comment by karmab** [comment]
implemented in https://github.com/karmab/kcli/commit/baf509a35c1060cbb24e5657b45d65225c924dde
actually using either 
kcli list --plans
or 
kcli plan --list / kcli plan -l
