### ISSUE TITLE
gzipped rhcos42 image breaks kcli download image

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#173]
It looks like RHCOS 4.2 downloaded image while running `kcli download image` (from https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.2/42.81.20200114.0/rhcos-42.81.20200114.0-qemu.qcow2) is gzipped. 

Not sure if it was gzipped previously and, anyway, it does not have gz extension. But running `file` command returns the following:

```
# file /var/lib/libvirt/images/rhcos-42.81.20200114.0-qemu.qcow2 
/var/lib/libvirt/images/rhcos-42.81.20200114.0-qemu.qcow2: gzip compressed data, was "rhcos-42.81.20200114.0-qemu.qcow2", last modified: Tue Jan 14 09:19:51 2020, from Unix, original size modulo 2^32 2012938240
```

As kcli tries to use that image as-is, libvirt refuses to start any VM from that as one would expect.

Manually gunzipping the image workarounds the issue.

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/25b621e510f20637e45dd8126e3ef3075d7a66ea
