### ISSUE TITLE
Unclarity: network in plan not assigned to instances

### ISSUE THREAD

**Issue by cherusk** [karmab/kcli#178]
I've formed a plan with instances and a network, refer to currrent here:
https://github.com/cherusk/godon/blob/test_micro_stack/testing/infra/machines.yml#L3

In this run, the network is clearly coming up, but is not assigned to the instances which it should contain nominally:
https://travis-ci.com/cherusk/godon/builds/149010558#L2596

In other words, the instances do not get an IP from this network assigned. According to doc, it should happen via the network internal DHCP.

Please advice, I'm confused.

**Comment by karmab** [comment]
yes, vm should get an ip from this network as the default libvirt definition enables dhcp

**Comment by cherusk** [comment]
Saw that code stretches, but it's really not happening. Latest run, https://travis-ci.com/cherusk/godon/jobs/288063189

+-----------+--------+-----+---------------------------------------+--------------+--------------+--------+

|    Name   | Status | Ips |                 Source                |     Plan     |   Profile    | Report |

+-----------+--------+-----+---------------------------------------+--------------+--------------+--------+

|  sink_vm  |   up   |     | Fedora-Cloud-Base-30-1.2.x86_64.qcow2 | micro_fedora | micro_fedora |        |

| source_vm |   up   |     | Fedora-Cloud-Base-30-1.2.x86_64.qcow2 | micro_fedora | micro_fedora |        |

+-----------+--------+-----+---------------------------------------+--------------+--------------+--------+

**Comment by karmab** [comment]
hum, you would have to wait a bit before ip provided by dhcp actually appears

**Comment by cherusk** [comment]
Quite valid.

**Comment by cherusk** [comment]
Now I put a wait of ~4 mins,
+ sleep 240

Has still not been assigned. I'll look into internas.

**Comment by cherusk** [comment]
Couldn't cure the DHCP leasing. Nigh, looking at your internas, you're doing exactly what libvirt specifies. Satically assigned for now, that seems to work.

Hence, closing as rather case for libvirt folks.

Cheers
