### ISSUE TITLE
Testing: insuffcient current setup/invisible flows 

### ISSUE THREAD

**Issue by cherusk** [karmab/kcli#188]
@karmab 
I'm inclined to bring about some level of more smoke/automatic integration testing for the libvirt/kvm part of the code.

Before doing that, I'd like to synchronize as I might am lacking visibility as to that are.

Looking at the travis flow, that's too minimalistic, mostly for build/push.

Wondering, how/where are you doing more expedited testing flow? Manually based on the sample plans? As you're at REDHAT, would you have resources for such CI flows?

**Comment by karmab** [comment]
i need to improve ci covering, for sure. beyond the basics done in travis.
btw, side note, you can join #kcli slack channel in kubernetes workspace to speed up discussions

**Comment by cherusk** [comment]
As said, I'm prepared to contribute.
Closing since joining the proposed channel.
