### ISSUE TITLE
[RFE] Add openindiana support

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli#198]
To celebrate the [2020.04 release](http://docs.openindiana.org/release-notes/2020.04-release-notes/) of openindiana, it would be nice to be supported in kcli.

According to the [FAQ](https://www.openindiana.org/documentation/faq/):

The OpenIndiana project is the open source community which develops, maintains, and supports the OpenIndiana distribution, an illumos based Unix-like operating system derived from OpenSolaris. The purpose of the OpenIndiana Project is to ensure the continued availability of an openly developed distribution based on OpenSolaris. The OpenIndiana project is also a continuation of the collaborative effort and community spirit of the OpenSolaris project.

**Comment by e-minguez** [comment]
There is also another illumos distribution called OmniOS here -> https://omniosce.org/download.html

**Comment by karmab** [comment]
sadly, those distributions don't provide a cloud image ready to be used :(
one can still boot a vm from their iso though (they actually support virtio disks which make it quite simple): 

![image](https://user-images.githubusercontent.com/1840387/81156320-1e99b180-8f86-11ea-9f5a-87097924db90.png)

![image](https://user-images.githubusercontent.com/1840387/81156458-40933400-8f86-11ea-938e-99bd9681e701.png)
