### ISSUE TITLE
Please add klist to the entry points

### ISSUE THREAD

**Issue by oz123** [karmab/kcli#202]
Currently, klist isn't included in the Debian or Python package.

To do that you will probably need to make `extras` included in `find_packages` or simply move it to a new location.

Would you accept a PR ?

**Comment by karmab** [comment]
PRS are always welcome!
i think i've solved it in https://github.com/karmab/kcli/commit/dca8e4a875890198ebf5c9723f9e93269352253e
please confirm!

**Comment by oz123** [comment]
Awesome, thanks for the quick response. See my tiny comment.
