### ISSUE TITLE
Specifying vm name when executing 'kcli ssh vm'

### ISSUE THREAD

**Issue by sabinaaledort** [karmab/kcli#205]
When executing 'kcli ssh _vm_' command (mentioned in quick start) had to specify the newly created vm **name** instead of _vm_.

**Comment by karmab** [comment]
fixed doc in https://github.com/karmab/kcli/commit/f683a76edd1160a0eafd1507efe153470a867071
note that full doc is at https://kcli.readthedocs.io/en/latest/
