### ISSUE TITLE
deploying ansible playbook from profile

### ISSUE THREAD

**Issue by jameski83** [karmab/kcli#214]
From the help documents it looks like deploying a playbook via a profile is available so that it runs when then vm is provisioned, however when I add it it just says retrieving ip of vm several times then errors with 'Kvirt' object has no attribute '_ssh_credentials'. Looks like it isn't waiting long enough for the vm to provision. This is with a libvirt host.

I am adding a section to the profle as below

```
ansible:
 - playbook: frout.yml
   verbose: true
```

Running ansible commands manually using the dynamic inventory works fine after the VM has been given time to fully provision. Can you please advise if this functionality is available using profiles and that I am doing it correctly?

**Comment by karmab** [comment]
thanks for the report.
indeed, the ansible code was still using  _ssh_credentials function from the provider specific code, where as we moved this function to be common to all providers.
fixed (right now) in https://github.com/karmab/kcli/commit/cf9bacaff51e4e5246a992104e89b647d43d40ed, upgrade should do the trick!

**Comment by jameski83** [comment]
wow thanks for the fast response! I have updated and tried to create a vm again with the profile with various playbooks that have been tested externally and I get the below messages ;

`Deploying vm jame from profile fed32...
Retrieving ip of jame...
Retrieving ip of jame...
Retrieving ip of jame...
Retrieving ip of jame...
Retrieving ip of jame...
Retrieving ip of jame...
Retrieving ip of jame...
Retrieving ip of jame...
No ip found. Cannot ssh...
Traceback (most recent call last):
  File "/usr/bin/kcli", line 11, in <module>
    load_entry_point('kcli==99.0', 'console_scripts', 'kcli')()
  File "/usr/lib/python3.8/site-packages/kvirt/cli.py", line 3131, in cli
    args.func(args)
  File "/usr/lib/python3.8/site-packages/kvirt/cli.py", line 921, in create_vm
    result = config.create_vm(name, profile, overrides=overrides, customprofile=customprofile, wait=wait)
  File "/usr/lib/python3.8/site-packages/kvirt/config.py", line 794, in create_vm
    ansibleutils.play(k, name, playbook=playbook, variables=variables, verbose=verbose, user=user,
  File "/usr/lib/python3.8/site-packages/kvirt/ansibleutils/__init__.py", line 47, in play
    if '.' in ip:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by karmab** [comment]
i ve pushed additional fixes to cover those cases where the ip doesnt get retrieved (for instance if you re running on a network without dhcp, and you didnt specify a fixed ip neither).
In your case though, i would first ask why no ip gets retrieved over time.
Does an ip show up when you run `kcli list vm` or `kcli info vm $your_vm` ?
Also feel free to join on slack for a live debugging session ;)

**Comment by jameski83** [comment]
sure happy to go on slack, although when I click the link on github it just takes me to a "sign into your workspace" page, not sure what to put in here?

**Comment by karmab** [comment]
i should make it clear that it's hosted on kubernetes slack so you need to sign in at https://slack.k8s.io first

**Comment by karmab** [comment]
handled through several commits
