### ISSUE TITLE
Keep the github releases updated

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli#217]
Latest github release is quite old... it would be nice to keep them up to date or just remove the releases if they are not being updated.

**Comment by karmab** [comment]
yes, since we're working in rolling release, i want to actually remove all the releases.
Need to do so with github api

**Comment by karmab** [comment]
removed all releases and tags.
For the record i used https://github.com/stevemao/github-remove-all-releases npm for the releases
and for the tags the following oneliner `git tag -l | xargs -n 1 git push --delete origin`
