### ISSUE TITLE
[RFE] Check for broken links in the docs

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli#218]
Such as https://kcli.readthedocs.io/en/latest/#profiles-configuration `You can use the profile file sample to get you started`

Hint: https://github.com/marketplace/actions/broken-link-check

**Comment by karmab** [comment]
I started added the suggested action and then I remembered that adding a random action implies a security risk while i can manually address the few links that the doc has (for instance, when generating the rst data from markdown, which is a manual step run before committing)
