### ISSUE TITLE
Deploying OCP 4.6 with less than 3 masters, cause an error

### ISSUE THREAD

**Issue by Avielyo10** [karmab/kcli#228]
```bash
ERROR Cluster operator authentication Degraded is True with WellKnownReadyController_SyncError: WellKnownReadyControllerDegraded: need at least 3 kube-apiservers, got 1 
INFO Cluster operator authentication Available is False with WellKnown_NotReady: WellKnownAvailable: The well-known endpoint is not yet available: need at least 3 kube-apiservers, got 1 
INFO Cluster operator insights Disabled is False with AsExpected:  
FATAL failed to initialize the cluster: Cluster operator authentication is reporting a failure: WellKnownReadyControllerDegraded: need at least 3 kube-apiservers, got 1
```

**Comment by karmab** [comment]
this is a consequence of https://github.com/openshift/cluster-authentication-operator/blob/18517f766d1320c3f36bee72fcc1c0c9431962d7/pkg/controllers/readiness/wellknown_ready_controller.go#L174-L190
you can manually work around with the following command `oc patch authentication cluster -p='{"spec": {"unsupportedConfigOverrides": {"useUnsupportedUnsafeNonHANonProductionUnstableEtcd": true}}}' --type=merge`
that i m gonna incorporate in the code

**Comment by karmab** [comment]
should be addressed in https://github.com/karmab/kcli/commit/e9f53a514ae8aba7dee77de1dcadd9826216b8ac
Please confirm ;)

**Comment by Avielyo10** [comment]
Got it thanks!

**Comment by karmab** [comment]
just for the record, i had a typo that i edited in the PR and in the comment.
If you want to validate manually, this is your command:

```
oc patch authentication cluster -p='{"spec": {"unsupportedConfigOverrides": {"useUnsupportedUnsafeNonHANonProductionUnstableOAuthServer": true}}}' --type=merge
```

**Comment by karmab** [comment]
so, the correct manual command was actually

```
oc patch authentications.operator.openshift.io cluster -p='{"spec": {"managementState": "Managed", "unsupportedConfigOverrides": {"useUnsupportedUnsafeNonHANonProductionUnstableOAuthServer": true}}}' --type=merge
```
ie the domain part of the crd needs to be specified

**Comment by karmab** [comment]
confirmed the fix works and duplicated in the code

**Comment by Avielyo10** [comment]
Thanks @karmab !
