### ISSUE TITLE
[BUG]kcli fails to be installed on Fedora 25, needs redhat-rpm-config dependency.

### ISSUE THREAD

**Issue by jtudelag** [karmab/kcli#23]
sudo pip install kcli
Collecting kcli
  Using cached kcli-4.2.tar.gz
Collecting libvirt-python>=2.2.0 (from kcli)
  Using cached libvirt-python-2.5.0.tar.gz
Collecting docker (from kcli)
  Using cached docker-2.0.2-py2.py3-none-any.whl
Collecting Click (from kcli)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting iptools (from kcli)
  Using cached iptools-0.6.1-py2.py3-none-any.whl
Collecting netaddr (from kcli)
  Using cached netaddr-0.7.19-py2.py3-none-any.whl
Requirement already satisfied: PyYAML in /usr/lib64/python2.7/site-packages (from kcli)
Collecting prettytable (from kcli)
  Using cached prettytable-0.7.2.zip
Collecting websocket-client>=0.32.0 (from docker->kcli)
  Using cached websocket_client-0.40.0.tar.gz
Requirement already satisfied: requests!=2.11.0,!=2.12.2,>=2.5.2 in /usr/lib/python2.7/site-packages (from docker->kcli)
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker->kcli)
  Using cached backports.ssl_match_hostname-3.5.0.1.tar.gz
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/site-packages (from docker->kcli)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/site-packages (from docker->kcli)
Collecting docker-pycreds>=0.2.1 (from docker->kcli)
  Using cached docker_pycreds-0.2.1-py2.py3-none-any.whl
Requirement already satisfied: urllib3==1.15.1 in /usr/lib/python2.7/site-packages (from requests!=2.11.0,!=2.12.2,>=2.5.2->docker->kcli)
Installing collected packages: libvirt-python, backports.ssl-match-hostname, websocket-client, docker-pycreds, docker, Click, iptools, netaddr, prettytable, kcli
  Running setup.py install for libvirt-python ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-II5Pqu/libvirt-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-C6qnTb-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    /bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
    /usr/bin/python generator.py libvirt /usr/share/libvirt/api/libvirt-api.xml
    Found 415 functions in /usr/share/libvirt/api/libvirt-api.xml
    Found 0 functions in libvirt-override-api.xml
    Generated 343 wrapper functions
    /usr/bin/python generator.py libvirt-qemu /usr/share/libvirt/api/libvirt-qemu-api.xml
    Found 5 functions in /usr/share/libvirt/api/libvirt-qemu-api.xml
    Found 0 functions in libvirt-qemu-override-api.xml
    Generated 3 wrapper functions
    /bin/pkg-config --atleast-version=1.0.2 libvirt
    /usr/bin/python generator.py libvirt-lxc /usr/share/libvirt/api/libvirt-lxc-api.xml
    Found 4 functions in /usr/share/libvirt/api/libvirt-lxc-api.xml
    Found 0 functions in libvirt-lxc-override-api.xml
    Generated 2 wrapper functions
    running build_py
    creating build/lib.linux-x86_64-2.7
    copying build/libvirt.py -> build/lib.linux-x86_64-2.7
    copying build/libvirt_qemu.py -> build/lib.linux-x86_64-2.7
    copying build/libvirt_lxc.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building 'libvirtmod' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/build
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -I/usr/include/python2.7 -c libvirt-override.c -o build/temp.linux-x86_64-2.7/libvirt-override.o
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-II5Pqu/libvirt-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-C6qnTb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-II5Pqu/libvirt-python/

$ dnf provides /usr/lib/rpm/redhat/redhat-hardened-cc1 
Last metadata expiration check: 1:20:16 ago on Sun Jan 22 20:34:20 2017.
redhat-rpm-config-45-1.fc25.noarch : Red Hat specific rpm configuration files
Repo        : updates

redhat-rpm-config-44-1.fc25.noarch : Red Hat specific rpm configuration files
Repo        : fedora

**Comment by karmab** [comment]
updated README with this information
thanks!
