### ISSUE TITLE
Packagecloud: Bandwidth or Storage Limit Exceeded

### ISSUE THREAD

**Issue by felinira** [karmab/kcli#240]
packagecloud won't let me download the deb files. It throws the error message 

> Bandwidth or Storage Limit Exceeded

**Comment by karmab** [comment]
yeah, it seems i have hit some storage limit, although i did some cleaning today....
I' ve decided to migrate to cloudsmith instead to host debian package and have updated the doc accordingly.
You should be able to install the deb with the following instructions:

```
curl -1sLf https://dl.cloudsmith.io/public/karmab/kcli/cfg/setup/bash.deb.sh | sudo -E bash
apt-get update
apt-get -y install python3-kcli
```
