### ISSUE TITLE
Feature request / question - The option to use K3OS

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#245]
I've given the code a look and so far I haven't been able to spot the option to use K3OS as the OS for deployed K3S nodes.

Would that become an option? Or is it already?

Thank you very much.

N.B.

- Find K3OS [here](https://github.com/rancher/k3os)

**Comment by larssb** [comment]
Anyone?

**Comment by karmab** [comment]
ah, sorry for the delay,
So i had a look at k3os of which i was unaware, but it seems to be iso based, which makes it a little bit more complicated to incorporate in the existing create k3 workflow.
I ll have a look nevertheless to evaluate whether it s feasible to have deployment automated

**Comment by larssb** [comment]
Thank you very much @karmab ... that's very kind of you. K3OS is pretty cool. It's also used in the [RancherLabs Harvester](https://github.com/rancher/harvester) product.

I'll patiently await an update on this issue when you've had time to give it a look.

**Comment by larssb** [comment]
I think this should be closed as RancherLabs likely won't continue K3OS in the long run. See this comment from the lead developer on Harvester, Mr. Sheng > https://youtu.be/87_ODymEGC0?t=1379  <-- where he basically refers to Suse buying up RancherLabs being the reason behind it. Makes sense, at least to me, as Suse is a OS developer. So they will likely create a minimal container oriented OS. Hopefully the OS will be developed together with the great minds from RancherLabs.
