### ISSUE TITLE
In libvirt kcli creates multiple DNS records  

### ISSUE THREAD

**Issue by wzzrd** [karmab/kcli#252]
I have the default network in libvirt w/ the default cidr 192.168.122.0/24. I have edited that network to run with domain nontoonyt.lan. 

When I use `kcli create dns -d nontoonyt.lan -i 192.168.122.200 foobar` the result is not just a nontoonyt.lan record in the XML config for the libvirt default network:
```
  <dns>
    <host ip="192.168.122.200">
      <hostname>foorbar</hostname>
      <hostname>foobar.default</hostname>
      <hostname>foobar.nontoonyt.lan</hostname>
    </host>
```

I'm not sure whether this is expected or not, but it feels strange.

**Comment by karmab** [comment]
this is expected, although i agree it should be better not to create those extra records when you indicate a specific domain

**Comment by wzzrd** [comment]
Ah, ok. Well, too bad I guess. It just looks weird :)

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/afd65caf97542f4a85c347e0b085ab38b67b0bb1 !

**Comment by wzzrd** [comment]
Awesome!!
