### ISSUE TITLE
kcli shouldn't install as kvirt

### ISSUE THREAD

**Issue by mikelolasagasti** [karmab/kcli#254]
kcli is installed in `/usr/lib/python3.9/site-packages/kvirt/` and should be using `/usr/lib/python3.9/site-packages/kcli/` to reflect project name.

**Comment by karmab** [comment]
kvirt is the name of the library, while kcli is the name of the client on top of it

**Comment by larssb** [comment]
Doesn't the answer from Mr. @karmab solve your issue @mikelolasagasti ???

**Comment by karmab** [comment]
i understand it might be as slightly confusing, but it also comes from the fact that we really want to differentiate the cli from the lib, and it s too late probably to go with `kclilib`
