### ISSUE TITLE
kcli scale kube openshift doesn't find cluster name with paramfile if not in the paramfile

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#258]
Let's use a paramfile like this:
```
version: stable
domain: leeloo.example.net
image: rhcos-46.82.202011111640-0-qemu.x86_64.qcow2
masters: 3
workers: 2
api_ip: 192.168.194.254
network: leeloo
master_memory: 16384
bootstrap_memory: 8192
```

This param file works like a charm to install a cluster with `kcli create kube openshift --paramfile <blablabla>`.

However, if I use it for scale, it doesn't get cluster name from command line like when creating the cluster:
```
$ kcli scale kube openshift --paramfile $(pwd)/parameters-leeloo.yml -w 3 leeloo
Scaling on client local
Cluster directory /root/.kcli/clusters/testk not found...
```

Messing around a bit with pdb, I could find that the bad cluster name is set [here](https://github.com/karmab/kcli/blob/master/kvirt/openshift/__init__.py#L230), when it is unconditionally read from `overrides` variable and `cluster` variable (which seems to be read from command line) is ignored. 

The `overrides` variable [seems to be read from the paramfile](https://github.com/karmab/kcli/blob/master/kvirt/cli.py#L1503) and contain the information from paramfile, as per this fragment of my pdb session:
```
> /usr/lib/python3.6/site-packages/kvirt/cli.py(1503)scale_openshift_kube()
-> overrides = common.get_overrides(paramfile=paramfile, param=args.param)
(Pdb) n
> /usr/lib/python3.6/site-packages/kvirt/cli.py(1504)scale_openshift_kube()
-> if workers > 0:
(Pdb) print(overrides)
{'version': 'stable', 'domain': 'leeloo.example.net', 'image': 'rhcos-46.82.202011111640-0-qemu.x86_64.qcow2', 'masters': 3, 'workers': 2, 'api_ip': '192.168.194.254', 'network': 'leeloo', 'master_memory': 16384, 'bootstrap_memory': 8192}                                                                             
(Pdb) overrides.get('cluster')
(Pdb) overrides.get('cluster','testk')
'testk'
```

So as a workaround, I just added `cluster: leeloo` to the paramfile and now it works.

However, I'd expect either:
 - Cluster name to be read from CLI (I guess this one makes more sense)
 - `cluster: leeloo` to be required for all the operations (including creation) and it to not be required at command line if specified at paramfile (I'd need to double-check if that is a requirement for `kcli create kube openshift`).
 
 Also not sure if other commands are affected, as I only checked `kcli scale kube openshift`.

**Comment by karmab** [comment]
hopefully this should be fixed by https://github.com/karmab/kcli/commit/07ffe6ad447d404fec0a3655ea111240111b9f64
so that:
- the cluster parameter from a paramfile/command line always has precedence. It allows you to run kcli create cluster openshift without any additional args.
- kcli scale cluster openshift can also take its cluster from a parameter file (although it s probably more intuitive to specify target cluster.
