### ISSUE TITLE
[RFE] Plan resources should be treate as a whole, and not individually.

### ISSUE THREAD

**Issue by jtudelag** [karmab/kcli#28]
As a plan is a set of resources, all the operations regarding plans (kcli plan ...)should be applied to all the resources of the plan. For individual actions, you can use kcli normally.

So for example, "kcli plan --list" should list vms and containers. The same way for the rest of the operations.

On the other hand I would deprecate the use of the container flag (-c) for plans, as If this RFE is implemented, It would not make any sense.

**Comment by karmab** [comment]
i gave a try to this model for a while back then, but it felt cumbersome to use.
so the current way you handle plans go like this
kcli plan  allows you to start/stop/delete/create the entire plan. it operates on vms exclusively.
but it should also stop containers if they belong to the plan,  which it doesnt currently indeed, which means coding:
-  the plan information in the metadata of the container
- adding the stop logic for the containers belonging to the plan . 

to list objects of a plan, you use *kcli list --plans*. in general , kcli list is the exclusive entry points to list objects.
again, in the case of the plan, this listing only reports vms but should include containers ( and possibly other objects of the plans

**Comment by karmab** [comment]
what's left on this topic now that containers have their own subresource:

- kcli stop/start plan should also stop containers belonging to the plan
- kcli list plan should include extra columns to list containers and networks belonging to the plan
