### ISSUE TITLE
[RFE] Slack channel cannot be used without invite to slack instance

### ISSUE THREAD

**Issue by iranzo** [karmab/kcli#282]
Currently the readme states slack channel, but that's not valid until an invite for the slack instance is provided

**Comment by karmab** [comment]
is there anything we can do about it?

**Comment by iranzo** [comment]
Yes, add two links, one for the invite to the slack instance and another one for the chat itself

**Comment by iranzo** [comment]
For the invite: https://slack.k8s.io/
For the channel: https://kubernetes.slack.com/archives/CU76B52JE

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/c6a4fb22a13bd671d74a8bc642fbfdfcc35eb1a3
