### ISSUE TITLE
Misleading error message if bad contents in profile

### ISSUE THREAD

**Issue by dgibson** [karmab/kcli#297]
I mistakenly guessed at a possible profile parameter leading to this behaviour:

```
$ cat .kcli/profiles.yml
default:
  image: Fedora-Cloud-Base-34-1.2.x86_64.qcow2
  type: q35
$ kcli create vm -p default test
Using local libvirt as no client was specified...
Deploying vm test from profile default...
Profile default not found. Using the image as profile...
test not created because you don't have image default
```

Obviously the profile *does* exist, it just has a bad parameter.  Validating the parsing of the profile and giving an error related to that would be much more useful.

**Comment by karmab** [comment]
fair enough

**Comment by karmab** [comment]
while i fix it, note that, beyon reading the doc, you can use `kcli list keyword` to show valid keys (and their current value)

**Comment by karmab** [comment]
sorry for the delay!!!
fixed in https://github.com/karmab/kcli/commit/9f890148132aa3577042fb926bd243d0e2909d0c
