### ISSUE TITLE
Add forwarders to network

### ISSUE THREAD

**Issue by wzzrd** [karmab/kcli#298]
Would you accept code to add forwarders to the network XML?

This is useful for me to prevent DNS loops on Fedora 34, where the dnsmasq instance on 127.0.0.53 can request DNS records from libvirt DNS instances, which then in turn can lookup those DNS records on 127.0.0.53 ad infinitum.

Background is that you can configure the dnsmasq instance that is refered to in /etc/resolv.conf to check for DNS names in the libvirt instances of dnsmasq. But by default - or so it looks to me, anyway - the libvirt dnsmasq instances will server IPv4 records only.

If you open a web page on a VM that you have resolved through DNS (127.0.0.53 forwarding to the libvirt instance), it will ask for both an A record and an AAAA record. The A record is served, the AAAA record is forwarded again, back to 127.0.0.53. This will eventually time out and make DNS resolving for local VMs really slow.

I might be doing this wrong of course, but I have found that breaking that loop (through adding an explicit forwarder that is not 127.0.0.53), I get instant responses from the host command and opening web pages on local VMs.

Example code: https://github.com/wzzrd/kcli/tree/add_forwarder_to_create_network

**Comment by karmab** [comment]
sorry for the delay, it seems i m missing some notification thing here. Reading

**Comment by karmab** [comment]
i enjoy the use of "ad infinitum"

**Comment by karmab** [comment]
can you provide an example of the resulting xml?

**Comment by karmab** [comment]
nevermind, this is properly documented at https://libvirt.org/formatnetwork.html#elementsAddress

**Comment by karmab** [comment]
added feature in https://github.com/karmab/kcli/commit/ae9c952a69847635274c93883cc1e9ea386272ce
i ll update the doc but so you know, you can consume it either on command line

````
kcli create network -c 192.168.52.0/24 -P forwarders=['{"domain": "froutos.karmalabs.com", "address": "192.168.122.207"}'] magico
```

or you can use it in a plan file for instance

```
magico:
 type: network
 cidr: 192.168.52.0/24
 forwarders:
 - domain: froutos.karmalabs.com
   address: 192.168.122.207
```

**Comment by wzzrd** [comment]
Wow you're fast :)
Thanks
