### ISSUE TITLE
Support the .yaml file ending for the KCLI config file

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#307]
People have expectations. So do my colleagues 😄 . They've been using KCLI for a week plus now and had trouble getting `kcli` to work from the cmdline and therefore resorted to the `Docker` way of running `KCLI`, as well as creating a custom script that would enforce `kcli` to "find" the `config.yml` file.

Back from vacation I troubleshooted what gave them issues and found that they had indeed used the `.yaml` file ending for the `kcli` `config.yml` file.

I've just skimmed the `kcli` code and it looks like there's many places in the code that needs to be updated, if `kcli`, is to support using the `.yaml` file ending for the `config` file.
I think support for that would be great ... I see no reason not to ... I think `kcli` should be careless whether the `kcli` `config` file have the `.yml` or the `.yaml` file ending. As long as it's a YAML one.

👍

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/adfd6e3aad9d07acc1d303fb1aa00d7e9c77972c
