### ISSUE TITLE
K3s cluster creation error

### ISSUE THREAD

**Issue by alexander-bruun** [karmab/kcli#309]
Hello

I'm currently trying to use kcli to create a K3s cluster with VSphere using the following plan:
https://gist.github.com/alexander-bruun/887634f6e1237a4b90912f8de2638e82

When i then execute:
`kcli create kube k3s --paramfile $kcliPlanFilePath $clustername`

I get the following error:
![image](https://user-images.githubusercontent.com/87643857/126986407-6ffd7c4a-854e-4a33-874a-5bf5f639211b.png)
The error occured after switching to a new Network in the plan. (I also updated the network in .kcli/config)

**Comment by larssb** [comment]
We've seen this before @karmab when I initially deployed K3s to our VMWare vSphere platform. And you implemented support for virtual switches. E.g. > https://github.com/karmab/kcli/commit/daddb52431f11655857cbb8103255d3b9e5c76a1 ... so, now that we have to change the network we deploy to in vSphere, this err. pops up. Can you figure out why this might occur. And feel free to ask me or my colleague for more info.

Have a great 1 😄

**Comment by karmab** [comment]
Hello, i m trying indeed to figure out how this error could be triggered, which is indeed related to dvs

**Comment by karmab** [comment]
i think what fails is updating the network of the (primary) nic of the vms because your new network is different from the one in the image (which i guess was the one you originally were indicating in the parameter file)

**Comment by karmab** [comment]
can you indicate how many nics the image/template used has?

**Comment by larssb** [comment]
We're doing nothing to add extra nics. So I would say one. And:

```txt
i think what fails is updating the network of the (primary) nic of the vms because your new network is different from the one in the image (which i guess was the one you originally were indicating in the parameter file)
```

_I agree_

**Comment by alexander-bruun** [comment]
Here is the kcli config that I'm using:
https://gist.github.com/alexander-bruun/bdb85b17c33c829a6bbb16f8f43a506c

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/5a597c7a25689cbf58a4d759b4ae482ba1f9523f
the issue was that a reset of an additional attribute, the portKey, was needed when switching the dvs information in the first nic from the template to the target vm
