### ISSUE TITLE
[Feature request] Support relative paths for the `files` parameter in **plans**

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#325]
We've had a talk on Slack on the `files` parameter. That resulted in that parameter to support and respect absolute paths if one sets `currentdir: True` .... it would be wonderful if the same parameter also supported relative paths. Relative to the location of a plan file itself.

Would this be possible?

Thank you very much

**Comment by karmab** [comment]
that s the default behaviour, ie relative paths are always prepended the plan file dir

**Comment by LarsBingBong** [comment]
Hmm alright. Let's abandon this then.
