### ISSUE TITLE
Use compressed templates

### ISSUE THREAD

**Issue by mikelolasagasti** [karmab/kcli#34]
CentOS provides qcow images compressed that are 1/3 size of the normal version

CentOS-7-x86_64-GenericCloud.qcow2 1.3G	 
CentOS-7-x86_64-GenericCloud.qcow2.xz 426M

**Comment by karmab** [comment]
that would make sense, but i believe you can't boot from a compressed image, so the image would have to be uncompressed anyway, so no storage gain anyway, just some bandwidth...
