### ISSUE TITLE
[BUG] isolated networks

### ISSUE THREAD

**Issue by wzzrd** [karmab/kcli#346]
The `-i` option in the cli results in a situation where the network is not isolated, but in routing mode instead if DHCP is no disabled as well. This is not what I want: I want an isolated network *with* DHCP :)

Problem happens around https://github.com/karmab/kcli/blob/b617471b6ec44d284898d2d8db43f048aaf9bff6/kvirt/providers/kvm/__init__.py#L2958 in combination with https://github.com/karmab/kcli/blob/b617471b6ec44d284898d2d8db43f048aaf9bff6/kvirt/cli.py#L2501

If you set the `-i` flag, you get no NAT, which is good. If you still want DHCP though, during libvirt network creation, natxml is set to `<forward mode='route'></forward>`. For an isolated network though, natxml should just remain unset.

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/23bf9b8f43178538b5982f7b982b6274099137b1
