### ISSUE TITLE
[CI] Pushing to your fork's master branch tries to run release CI jobs

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#348]
$TITLE basically summarizes it: When I push to my own fork's master branch, the CI job tries to push the .deb package, which is not a good idea to me. It fails due to the lack of an API key, but you might want to do a review on this.

**Comment by karmab** [comment]
this should hopefully fix it https://github.com/karmab/kcli/commit/82d77f4a2a0f4359a9c8c5817e6c8d397f14dddf
