### ISSUE TITLE
kcli stop plan planname "pulls the plug" and leads to potential filesystem corruption in VMs

### ISSUE THREAD

**Issue by dgonyier** [karmab/kcli#350]
I hit a situation where one of the nodes did not start back up after a 

```
kcli stop plan <plan name>
...
kcli start plan <plan name>
```
sequence.

`virsh console <vm name>` revealed that the node stopped the boot the sequence due to XFS corruption that could not automatically recover. I was able to manually fix the XFS corruption and get the node to start up again.

I am not exactly sure how kcli stops the nodes, but I assume it uses `virsh destroy`  which 'pulls the power plug' on a VM. Calling `virsh shutdown` would be more gentle as it 'presses the power button' which in term signals the Linux kernel in the VM to shutdown gracefully.

**Comment by karmab** [comment]
sorry for the trouble :(
fix at https://github.com/karmab/kcli/commit/6e2035fb92f4adbdc44b9e1fe19c1231f46deadf which introduces a `--soft` flag to be used with stop vm/stop plan/ restart plan
