### ISSUE TITLE
Fail gracefully on a `Folder.delete` err on VMWare, because of lack of permissions

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#361]
We get this err.

![image](https://user-images.githubusercontent.com/80959443/141272460-32c786ba-3ad8-42fa-9417-da0783d00d15.png)

In the case where the user, by which we access our VMWare/vSphere system with, do not have the `privilegeId = 'Folder.Delete'` permission.
This is kinda on us - as our VMWare admin do not want us to have this permission because the user we use for deploying to VMWare will then be able to delete VM's & folders that were not deployed with **KCLI**. So I think that's fair.

---

This issue is therefore a feature request. In short - would it be possible to make **KCLI** fail gracefully on this error so that one can use the `--foce` parameter in order to delete X content of a **KCLI** **plan**? Then if the folder holding the **KCLI** **plan** contents cannot be deleted => **KCLI** continues on and deploys the same **plan** again.

---

That would be great. Thank you!

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli#:~:text=karmab-,vsphere%3A%20capture%20exception%20when%20folder%20can%27t%20be%20deleted%20because%20of%20pe%E2%80%A6,-%E2%80%A6

**Comment by LarsBingBong** [comment]
Yeah works wonders

![image](https://user-images.githubusercontent.com/80959443/141320712-6eb15d1b-93a9-4462-8c87-45d6f25a3a85.png)

Great thanks
