### ISSUE TITLE
The info msg when using the **KCLI** `--force` parameter could be a tad more clear

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#362]
When there's nothing to delete <=> relative to using the `--force` parameter with **KCLI** then one get's this message:

![image](https://user-images.githubusercontent.com/80959443/141274429-3464d0e6-2571-49f1-a9e4-478df953667d.png)

The `Nothing to do or plan ....` part. This could be a tad clearer in my mind. As a suggestion mention that there's nothing to delete/erase/remove relative to using the `--force` parameter. So it's clear to the end-user that this is the source of the info msg.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/dd9a30dee01122883b58b3b9945fe51da61c324b
