### ISSUE TITLE
Strange behavior of `mkdir -v /minio-data{1..4}` in the `cmds` section of a **KCLI** plan

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#363]
in a plan - let's call it myplan.yml this is in the `cmds` section

```yaml
...
    - >
      mkdir -v /minio-data{1..4}
...
```
Checking the `cloud-init-output.log` and I see

```txt
- mkdir: created directory '/minio-data{1..4}'
```

and yes a `ls -la /` verifies that a folder named **minio-data{1..4}** is in the root of the sys disk. Reading up on `mkdir` one can read that  `mkdir` supports the `{0..10}` approach.

Annnnnd when ssh'ing into the box and then executing:

```bash
mkdir -v /minio-data{1..4}
```

all good - as the output is:

```txt
mkdir: created directory '/minio-data1'
mkdir: created directory '/minio-data2'
mkdir: created directory '/minio-data3'
mkdir: created directory '/minio-data4'
```

---

The above is rather strange. The workaround is easy - but it would be great that one is able to use the shortened/range approach on as may commands in the **KCLI** `cmds` section. As it shortens plan files and makes it easier to overview them.

This issue might not have anything to do with **KCLI**. I do have read up on YAML and whether `{}` needs to be escaped and as far as I've gotten the correct info, they do not.

Also I've tried different approaches **KCLI** YAML plan file wise.

e.g.

* `- >` for the multi-line approach
* `- |` for the script approach
* `""` for the quoting the `mkdir` cmd approach

---

Any hints or advise is also highly appreciated.

Thank you a million

**Comment by karmab** [comment]
i think it's OS specific.
i tested it with the following plan and it worked as expected

```
myvm:
  image: centos8
  cmds:
  - mkdir -v /minio-data{1..4}
```

**Comment by LarsBingBong** [comment]
Oh man - that's annoying. Super weird. That I can do it on the shell in ubuntu 20.04 but not via this automated fashion, via cloud-init behind the scenes.

I guess I'll just have to use my workaround.

**Comment by karmab** [comment]
here's a recap of a plan snippet that you can use to address these kind of issues

```
files:
- my_script.sh
cmds:
- bash /root/my_script.sh
```
