### ISSUE TITLE
Nested virtualization not being activated on vSphere/VMWare v7.0.2

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#366]
As a proof see this pic

![image](https://user-images.githubusercontent.com/80959443/141841122-8f5842f5-fe4b-4e59-ba31-b417cc859f52.png)

The highlighted checkbox should've been checked.

This happens when we're creating/rolling a K3s cluster with `kcli create kube k3s ....` and the following parameter `nested: true` has been set in X KCLI plan file.

I checked the code for the provider > https://github.com/karmab/kcli/blob/2c20f402a8bd3adb649be8b5ded59fd6371a1965/kvirt/providers/vsphere/__init__.py#L536 and it looks fine - according to > https://vdc-repo.vmware.com/vmwb-repository/dcr-public/723e7f8b-4f21-448b-a830-5f22fd931b01/5a8257bd-7f41-4423-9a73-03307535bd42/doc/vim.vm.ConfigSpec.html - search for **nestedHVEnabled**.

---

I'm pretty sure my former colleague raised this a while back. Finally got around to mention it ... as I'm rolling clusters up and down these days ... so bumping into it again and again as we need **nested virtualization** enabled on certain clusters.

Looking forward to hearing what this could be.

**Comment by karmab** [comment]
i believe https://github.com/karmab/kcli/commit/d95aa56f66130a641eec3ee1f1f1771e42049d9c is the fix, but please confirm

**Comment by LarsBingBong** [comment]
I sure will confirm whether or not this is the fix. Matches well with the "research" I did last evening on this. Where using `SmartConnectNoSSL` is mentioned - as if one do not use that approach, an older version of the vSphere API is used and that one do not expose the `nestedHVEnabled` property.

I'll update this issue when I've tried within the next couple of hours.

**Comment by LarsBingBong** [comment]
Nope unfortunately @karmab - this did not fix it. I'm vd95aa56 (2021/11/15) of **KCLI**. No cigar ... so it's something else.

**Comment by LarsBingBong** [comment]
Also now that we're looking at this. If it's not already possible, I would love to be able to control this on a node specific level - or at least at node type level. E.g. **nested** not used on `master/control-plane` nodes and **nested** IS USED on `worker` nodes.

**Comment by LarsBingBong** [comment]
The PR was merged and accepted and I'll therefore happily close this issues as resolved.
