### ISSUE TITLE
Problem handling if vm did not get an IP

### ISSUE THREAD

**Issue by Devp00l** [karmab/kcli#370]
Firstly kcli is great and works pretty well :)

My problem was that somehow a image which I've downloaded was broken. After reading through the documentation I found `kcli console $vm` which helped me identifying the root cause. I first thought something is wrong with my network setup as the vm's didn't got an IP. I removed the image and downloaded it again and it finally worked :)

I see some solutions here:
1. The documentation should point out in case of problems to use the console command to better observe what the vm is doing - as there is no debug setting.
2. In case of an VM not getting an IP the console command should be mention (with the same reason)
3. MD5 checks for images (don't know if inplace)
4. If an VM does not get an IP show multiple solution the user could do and let the user interactively choose what he wants to do - do that and try the failed command again (nice but of course a lot time consuming than the rest)

**Comment by karmab** [comment]
i feel mentioning the value of the console for such issues is a good idea.
Besides that, maybe there should be a md5 check sum when downloading images, indeed

**Comment by karmab** [comment]
i ve added:

- a mention in the doc about the fact that consoles can be used when ssh doesnt work
- a `--full` flag to the command list available-images to print the image url. This flag allows the user to manually get the checksum for a given image to do additional checks. I considered automating that part, but each distro stores the information in a way or another so I feel it's a bit of overkill to add this.
