### ISSUE TITLE
kcli delete plan of a non existing plan exit with return code 0

### ISSUE THREAD

**Issue by yuvalk** [karmab/kcli#372]
```
$ kcli delete plan cnfdb4-inst
Are you sure? [y/N]: y   
No objects found during deletion of plan cnfdb4-inst
[kni@cnfdb0 kcli-openshift4-baremetal]$ echo $?
0
```

it would be nice if it was erroring

**Comment by karmab** [comment]
I changed the message to be a warning, but I'm not sure whether return code should be a failure.
I feel it's fine to try deleting assets (for starting clean typically) regardless of whether they exist or not

**Comment by yuvalk** [comment]
return code should be used as means of signalling to (other) automation.

for example -
how can my external script, that calls kcli, know that a plan is entirely deleted and doesnt exist anymore?

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/764f4b3ea4f5ecb13c33c29d80ca8f2083d158c6

**Comment by yuvalk** [comment]
kudos,
TNX!
