### ISSUE TITLE
use formal Fedora containerdisk

### ISSUE THREAD

**Issue by dankenigsberg** [karmab/kcli#379]
KubeVirt project maintains https://quay.io/repository/containerdisks/fedora and keeps it up to date, unlike the [-demo images](https://github.com/karmab/kcli/blob/641e4580e5b66a1c1e71dd5c388d9f3ddccc615f/kvirt/providers/kubevirt/__init__.py#L34) which are used for kubevirt CI and demos. Please update the code to consume the formal image.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/0310e50f1faaee67b88423ac86ce17443901dd40

**Comment by dankenigsberg** [comment]
I am not an expert, but I am not convinced that this would work. I think that you have code below that assumes a specific format of the fedora repo name.

Also imho `:35` should better be dropped, as it is going to age and be replaced by newer versions which most users would prefer for their new VMs.
