### ISSUE TITLE
IPv6DualStackNoUpgrade FeatureGate should not be required on OCP 4.8+

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#386]
To the best of my knowledge, the `IPv6DualStackNoUpgrade` is no longer required since OCP 4.8, so it shouldn't be added on OCP 4.8+

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/e71bd3a858cdb02e7f79d97ed3adb401719991ee
