### ISSUE TITLE
VMware openshift deployment fails - needs resourcePool

### ISSUE THREAD

**Issue by mulbc** [karmab/kcli#389]
I'm trying to deploy a single-node-openshift on my vmware cluster, but I get this error:

```
~ kcli create kube openshift --paramfile=kcli-sno.yaml sno-test
Deploying on client bangalore
Deploying cluster sno-test
Using stable version
Using existing openshift-install found in your PATH
Using installer version 4.9.13
Using url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.9/49.84.202110081407-0/x86_64/rhcos-49.84.202110081407-0-vmware.x86_64.ova...
Grabbing image rhcos-49.84.202110081407-0-vmware.x86_64...
Got 'NoneType' object has no attribute 'resourcePool'
Please run kcli delete image --yes rhcos-49.84.202110081407-0-vmware.x86_64.ova
```

kcli-sno.yaml looks like this:

```
cluster: sno-test
domain: odf.ninja
version: stable
tag: "4.9"
masters: 1
workers: 0
memory: 16384
numcpus: 16
disk_size: 100
network: ProdNet
api_ip: 10.70.56.16
```

For the host config I pointed kcli to my vcenter URL.
I can't find a reference to a resourcePool in the documentation... I did provide a `pool` setting in my host config and set it to my vsan data store... please help

**Comment by karmab** [comment]
checking

**Comment by karmab** [comment]
do you mind sharing your vcenter kcli config, this error comes from https://github.com/karmab/kcli/blob/af2dd490faa4a3ac70c7bcd3c49dc928eb4a73dd/kvirt/providers/vsphere/__init__.py#L1277 because it is assumed your cluster does have a resource pool
