### ISSUE TITLE
Is there a similar tool in Go?

### ISSUE THREAD

**Issue by auwsom** [karmab/kcli#398]
Hello, love this tool. Is there a similar tool in Go? I'm trying to recommend it to a colleague and they want to run it on win/mac/linux without having a large python executable from PyInstaller. Thank you

**Comment by karmab** [comment]
Hello, to run my tool on those platforms, you can use the container, which works fine.
There are surely similar tools written on go ( i can think of terraform for instance), but they tend to focus on a specific platform (and generally libvirt is treated a second citizen class)
