### ISSUE TITLE
undercloud.conf has deprecated option

### ISSUE THREAD

**Issue by Rcarratalasanchez** [karmab/kcli#40]
The undercloud.conf in plans/openstack/tripleo/undercloud.conf (https://github.com/karmab/kcli/blob/master/plans/openstack/tripleo/undercloud.conf#L12) have discovery_iprange = 10.0.0.100,10.0.0.120, but this name is deprecated in osp10: 

Deprecated group/name - [DEFAULT]/discovery_iprange
inspection_iprange = 192.0.2.100,192.0.2.120

Use inspection_iprange instead.

**Comment by karmab** [comment]
this was fixed !
