### ISSUE TITLE
Proxmox support?

### ISSUE THREAD

**Issue by simcax** [karmab/kcli#402]
Are there any plans on extending this tool to include Proxmox support?

**Comment by karmab** [comment]
Hello, i've considered it a couple of times but so far, it hasnt been prioritized :(

**Comment by simcax** [comment]
Okay. I have tried to poke around a bit in the repo, and it seems to be all python. 
So maybe with some pointers, I could start looking into it? I am using proxmox, and would really like to use kcli

**Comment by karmab** [comment]
feel free to have a look indeed
