### ISSUE TITLE
cannot ssh using hostname from one vm to another

### ISSUE THREAD

**Issue by nizamial09** [karmab/kcli#406]
When I tried to ssh into a vm say `ceph-node-01` from `ceph-node-00` it gives the following error
```
[root@ceph-node-00 ~]# ssh root@ceph-node-01
ssh: Could not resolve hostname ceph-node-01: Name or service not known
```

but for the same if I use the ip address to ssh it succeeds.
```
[root@ceph-node-00 ~]# ssh root@192.168.100.101
Last login: Sat Feb 26 06:12:10 2022 from 192.168.100.100
```
It's working in `quay.io/karmab/kcli:2543a61` but when I am trying this in `quay.io/karmab/kcli:22.02` its broken.

**Comment by karmab** [comment]
i think you want to use kcli ssh root@ceph-node-01 instead (in both cases)

**Comment by karmab** [comment]
issue stalled, feel free to reopen if its still failing
