### ISSUE TITLE
FEATURE REQUEST - Add the option, for at a minimum the vSphere HCI, to umoun the ISO used when deploying a VM

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#410]
The title says pretty much it all. The use-case is however, that a VM can be blocked from being vMotioned on a VMWare platform if/when an ISO is still mounted to a VM.
Therefore, it would be preferable that an ISO used for deploying a VM is removed after a successful deploy.

> N.B. I'm stating at a minimum the vSphere HCI. However, this is likely nice for several other of the HCI platforms that KCLI integrates to.

Thank you

**Comment by karmab** [comment]
i believe it was addressed in https://github.com/karmab/kcli/commit/9fdc7295f5f32156bca2fe5f0df6856a0ae4a7db

**Comment by karmab** [comment]
fixed after https://github.com/karmab/kcli/commit/e09ff15941f86fc311b096100854e5713237b6dd
