### ISSUE TITLE
Nested flag not properly working on AMD processors.

### ISSUE THREAD

**Issue by elektito** [karmab/kcli#42]
kcli tries setting the "vmx" flag on guest processors when the `nested` flag is set (which, by default, it is), but "vmx" is an Intel extension. The equivalent AMD flag is "svm".

I was trying to fix this and send a pull request, but I encountered a slight problem. We will be needing to check current CPU features. I examined two options:

1. Using `/proc/cpuinfo`. This is obviously Linux-specific. I wasn't quite sure if `kcli` is supposed to be cross-platform or not. Is it?

2. Using the `py-cpuinfo` package which is cross-platform, but it is slow. It takes about a second to get current CPU features.

 There might be other options obviously.

**Comment by karmab** [comment]
For a quick workaround, have a look at
https://github.com/karmab/kcli/blob/master/samples/cputuning/cpu.yml
As an example of how to enable/disable cpu features.
Note it can be done in plan, profiles or in your general conf (kcli.yml)
It should still be addressed, but i m confident we can use the api call
correspondant to virsh capabilities to grab the proper flag

**Comment by elektito** [comment]
Yes, we can set `nested` to `false` and then set the `svm` flag but it sounds hackish and a bit ugly. As to using `virsh` for getting CPU features, do you mean that virsh/libvirt can give us the _host_ processor features? I did a quick search and it seems like virsh/libvirt can only help us with the guest, not with the host.

**Comment by karmab** [comment]
i believe this is fixed in https://github.com/karmab/kcli/commit/7190e791878d15afe34c89259926969cbbb14a68

this is the snippet that does the trick 
capabilities = self.conn.getCapabilities()
if 'vmx' in capabilities:
    nestedfeature = 'vmx'
else:
    nestedfeature = 'svm'

**Comment by elektito** [comment]
Yes, it's working. Thanks.
