### ISSUE TITLE
Add output -o name

### ISSUE THREAD

**Issue by fbac** [karmab/kcli#424]
In a kubectl style, add -o name, such as:

- List vm's by name

`kcli list vm -o name`

output:
```
master-0
master-1
master-2
```

- List networks or whatever other resource

`kcli list net -o name`

output:
```
default
baremetal
ipv6
test
```

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/100e712e4127427bb814deafdca056377fcb550a and https://github.com/karmab/kcli/commit/9cacf8e10ac3b0b708fdb4dafb95a6c3a3432544
