### ISSUE TITLE
Do not delete disks in use

### ISSUE THREAD

**Issue by fbac** [karmab/kcli#425]
Don't allow to delete disks alredy in use by a vm, current behavior allows it:

Get disk from vm:
```
]$ kcli show vm ansible-ci-target-2

[...]

diskname: vda disksize: 10GB diskformat: virtio type: qcow2 path: /var/lib/libvirt/images/ansible-ci-target-2_0.img
```

Remove it:
```
$ kcli delete disk /var/lib/libvirt/images/ansible-ci-target-2_0.img
Are you sure? [y/N]: y

Deleting disk /var/lib/libvirt/images/ansible-ci-target-2_0.img
Using ansible-ci-target-2 as vm associated to this disk
```

Suggestion:
- Do not delete disks in use by default.
- Ask for confirmation with `- y`

**Comment by karmab** [comment]
actually, kcli disks associated to a vm are easy to locate as they follow the pattern $vm_$number.img so you can use this nomenclature to locate them
