### ISSUE TITLE
kcli doesn't install in RHEL 9

### ISSUE THREAD

**Issue by pablomh** [karmab/kcli#436]
kcli seems to have a dependency on `python3-flask` which is not shipped in RHEL 9
(and won't be, it seems).
~~~
# dnf install kcli
Updating Subscription Management repositories.
Last metadata expiration check: 0:10:16 ago on Tue Jun 28 08:02:44 2022.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides python3-flask needed by kcli-99.0.0.git.202206280740.d5dd0ae-0.el9.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
~~~

**Comment by karmab** [comment]
following up in https://bugzilla.redhat.com/show_bug.cgi?id=2101740
worst case we will make the flask dependency as optional (since it's only used in expose and web workflow), but let' see if it can be avoided

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/pull/440 by migrating to bottle (which doesnt even need packaging, as it can be bundled in a single file)
