### ISSUE TITLE
Deploying on `VMWare` throws `vmodl.fault.InvalidArgument` on `A specified parameter was not correct: unitNumber`

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#443]
The full error

![image](https://user-images.githubusercontent.com/80959443/181506467-86c04fae-397b-4bf7-b61a-50062bd119ce.png)

I've identified this to be happening when setting `extra_worker_disks:` to more `> 4`. I haven't identified exactly the number where this breaks. But, I know that it works with `<= 4` and for sure do not work when the disk count is `> 8`.

The `vm's` when executing `kcli list vm` are marked as being `down`.

How can we troubleshoot this and what could be the culprit.

Thank you very much.

**Comment by karmab** [comment]
sadly it feels more like a pyvmomi specific issue since we increase this unitNumber with every disk addition, as visible here https://github.com/karmab/kcli/blob/fade7fbea1a3dd700b9619b2bdd700ab3aa46751/kvirt/providers/vsphere/helpers.py#L222

**Comment by LarsBingBong** [comment]
Can we do anything about it?

**Comment by karmab** [comment]
fixed here https://github.com/karmab/kcli/commit/e20daecc5ae884f9fb59b796a759752c25234fd1
