### ISSUE TITLE
`VM VM_NAME-4 not found`. Is there something with exactly VM number `4` and `kcli delete`?

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#444]
Interchanged nodes on a production cluster this Tuesday and got:

![image](https://user-images.githubusercontent.com/80959443/181512166-13760e9f-ca95-49bc-84bb-0e9bbcaf93da.png)

Then today on a test cluster and got:

![image](https://user-images.githubusercontent.com/80959443/181512316-d62b6966-739b-45d0-a9cf-5aa10bf7d46d.png)

---

Nothing major more of a curious error. But, anyways, would be great to not `error` when there is not error as the `VM` was properly deleted from `VMWare`.

Thanks

**Comment by LarsBingBong** [comment]
Hmmm maybe there's "just" _something_  in general. Just got it for `worker-name-5` as well.

See:

![image](https://user-images.githubusercontent.com/80959443/181512629-f4f666ba-5209-4370-b5e0-e12083181097.png)

**Comment by karmab** [comment]
what s the call where you are getting this?

**Comment by LarsBingBong** [comment]
This is the call:

```bash
echo -e "\n$(tput setaf 2)$(tput bold)<-------------> Deleting the VM representing $__memberNode <-------------> $(tput init)"
if (kcli delete -y vm "$__memberNode"); kcliDeleteErr=$?; (( kcliDeleteErr )); then
    echo -e "\n$(tput setaf 1)$(tput bold) #### Failed to delete the VM representing ${__memberNode}. $(tput init)"
    echo -e "$(tput setaf 1)$(tput bold) #### The exit code of [kubectl delete] was: ${kcliDeleteErr} $(tput init)"                
    exit "${kcliDeleteErr}"
fi
```

**Comment by karmab** [comment]
ah right, i remember now.
the message comes from trying to delete the node from cluster, which is something you re handling yourself

**Comment by karmab** [comment]
does it reproduce consistently?

**Comment by LarsBingBong** [comment]
Hmm let's let this one hang for some time. As we're running the logic that interchanges nodes in X Kubernetes clusters some more the coming weeks. That in itself should reveal whether this is possible to reproduce consistently.

**Comment by karmab** [comment]
to me, it feels like you're calling the delete vm twice

**Comment by LarsBingBong** [comment]
I've identified the root cause of this and it's not `kcli` related. It's some logic in the code we have. I'm sorry for the time spent on really nothing. Life at times I guess.

I'll close this relative to the above.
