### ISSUE TITLE
Executing `kcli list vm` while also executing `kcli delete cluter CLUSTER_NAME` `kcli` throws `KeyError: 'config'`

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#446]
Here a screenshot of the err:

![image](https://user-images.githubusercontent.com/80959443/182457306-e329fd2c-bc72-4648-8b41-81515434dcc3.png)

---

Not a showstopper. Just would be great if `kcli list vm` handled this gracefully.

Thank you 👍🏿

**Comment by LarsBingBong** [comment]
@karmab any input on this 1? 👍🏿

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/7e17709d6228dec16bf27217ef120751f7ddca3a
