### ISSUE TITLE
unable to download rocky

### ISSUE THREAD

**Issue by yuvalk** [karmab/kcli#451]
$ kcli download image rockylinux8
Using pool default
Using url https://dl.rockylinux.org/pub/rocky/8.5/images/Rocky-8-GenericCloud-8.5-20211114.2.x86_64.qcow2...
Grabbing image rockylinux8...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Image rockylinux8 not Added because Unable to download indicated image

**Comment by karmab** [comment]
works fine, make sure to run a recent enough version of kcli since rocky8 links had to be updated when older content (such as 8.5) got moved to their vault
