### ISSUE TITLE
Feature: add ability for a central, user supplied cloudinit

### ISSUE THREAD

**Issue by aussielunix** [karmab/kcli#460]
## Why

As a power user, it would be helpful if we can make use of the power and flexibility of cloudinit ourselves with a central, cloudinit file that is either a full replacement or is merged with kcli's cloudinit..

## Use Case

* To have a consistent username on all VMs regardless of OS
* trigger package update
* other power uses of cloudinit

## Notes

Currently this is possible but requires creating a new, unique `$vmname.cloudinit` file for each new VM.

One challenge I forsee is key/value clashes if the supplied cloudinit is merged.  
I guess this could be managed with some documentation and a list of 'banned key/values'
I am happy to test this out for you and help with the documentation.

Mick

**Comment by aussielunix** [comment]
Thanks @karmab 

> To have a consistent username on all VMs regardless of OS

https://github.com/karmab/kcli/commit/2e2f76e214e6396ef51b272c0afa96dbe6d513b3 https://github.com/karmab/kcli/commit/15d6e0327b075df6d2f3299d0bd5bb064f82a119 adds this.

Tested and it works.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/63330199c9414c4659a0557ecf9d56d61fe23fc6
