### ISSUE TITLE
`nopubkey` maybe not fully cleaned up.

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#461]
`nopubkey` is still referred https://github.com/karmab/kcli/blob/2e2f76e214e6396ef51b272c0afa96dbe6d513b3/kvirt/common/__init__.py#L286. However, in https://github.com/karmab/kcli/commit/555f62b12c32eee3f6755aa2067d48cf882f9c50 you're cleaning up.

Is this a mistake or an overseen leftover?

Thanks

**Comment by karmab** [comment]
fair enough, addressed in https://github.com/karmab/kcli/commit/2e2f7434e205a5aa2a1ee49714145b5741de27dd
