### ISSUE TITLE
When using `tempkey` _Overwrite (y/n)_ is asked. Pictures will tell more.

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#462]
See:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/5261530/190482367-99b6c8b6-cb58-447d-b920-b0578a188aea.png)

and

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/5261530/190482408-0a52734c-2b87-450e-a498-d51009a074a2.png)

as examples.

---

It can happen several times throughout a deployment cycle. Did a `ls -la /tmp/FOLDER_NAME` and yes, well no surprise, there was already `id_rsa*` files in the mentioned folder.

This is no major issue. But, maybe it would be an idea to clean up the temp. dir used after use? Would also be great in regards to not having SSH key files laying around in the global `/tmp` directory.

---

Generally I love to avoid any prompts for end-users of the "stuff" we use `kcli` for. I've given the `kcli` source code a look and it seems it just piggy backs on some standard `Python` temp. dir related code. E.g. https://github.com/karmab/kcli/pull/393

Any ideas and thank you very much

**Comment by karmab** [comment]
the tempdir is supposed to be cleaned up at the end of run, as visible here at https://github.com/karmab/kcli/blob/2e2f7434e205a5aa2a1ee49714145b5741de27dd/kvirt/config.py#L1083

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/be160482de346f49e8e2da7d316737172ebe8830
