### ISSUE TITLE
Clean up temp-kcli-key from ~/.ssh/authorized_keys after use. When tempkey = true in a KCLI parameter file

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#463]
So in https://github.com/karmab/kcli/issues/462 the `tmp` dir. was cleaned up. While investigating that ticket/issue I also found that the `temp-kcli-key` created in `~/.ssh/authorized_keys` is not removed after use by `kcli` from each deployed VM.

We would love to get that temp key in `~/.ssh/authorized_keys` away/cleaned up as well. The flow wherein this was experienced is the `K3s` cluster deployment flow.

---

Of course we could fix this ourselves via executing some cmd that will remove the temp key from authorized_keys over SSH. However, I think it's fair to want `kcli` to do it as it was `kcli` injecting the SSH key into `authorized_keys`.

Thank you

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/c54b5ac068cb2b57ae5b9350e469723a23536022

**Comment by LarsBingBong** [comment]
So reopen this?
