### ISSUE TITLE
move kcli.yml to ~/kcli/config.yml

### ISSUE THREAD

**Issue by mperezco** [karmab/kcli#47]
It could be more understandable, this way, that this is the configuration for kcli and is not related to profiles or templates.

**Comment by karmab** [comment]
lol i hadnt read this one but we actually had the same idea :)
done in 7.20 released just now and also creating ~/.kcli/profiles.yml for ... profiles

**Comment by mperezco** [comment]
If you update the COPR I'll try it ;-)

M*

**Comment by karmab** [comment]
copr and deb repos get updated on each pypy release.
give it 5 minutes and you can update ;)
