### ISSUE TITLE
Keepalived getting a random password as updated in > https://github.com/karmab/kcli/commit/5afc0eddb3224c09db0d574e9e5185e103cf073d does not work in the scale case

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#470]
Yesterday I updated an existing cluster with a home cooked engine for introducing change to live K3s clusters. The control-plane nodes ( whereon Keepalived is running ) are replaced one by one, with this engine.

However, when a new node is deployed with `kcli scale ...` the `kcli` `scale` operation does not seem to apply the same random `Keepalived` password as done on [LOC 101 in k3s __init__.py](https://github.com/karmab/kcli/blob/master/kvirt/k3s/__init__.py#L101) in he `kcli create` case.

I'm further discussing this issue on > https://github.com/karmab/kcli/pull/469 < what do you think?

Thank you

**Comment by LarsBingBong** [comment]
So I tested changing the keepalived password on a live cluster ... and it seems to pretty easy and minimally disruptive. But, still want your opinion on this.

Thanks

**Comment by karmab** [comment]
when a cluster is created, the random keepalived password is stored (in ~/.kcli/clusters/$cluster/kcli_parameters.yml) and this data is evaluated when scaling.
So the password should be the same, unless scaling from some other place

**Comment by LarsBingBong** [comment]
It's because we're using scaling to introduce change. E.g. to update K3s to a new `Kubernetes` version. And to do that old nodes are removed in bulk ( if possible ) and new ones introduced.

So, yes the old keepalived password is used. However, what we would like is that a new unique one is generated. By I agree - if that's what you would answer - that this is not intended in the scale case ... as scaling is done to "something" already existing and therefore shouldn't change configuration as we're talking about here.

Thanks

**Comment by karmab** [comment]
discussed workflow on slack so closing this
