### ISSUE TITLE
Sys disk. on Ubuntu not always getting sda as the identifier. This causes issues with further disk related bootstrapping

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#473]
So when we create `worker` nodes to be a part of a `K3s` cluster. These nodes gets a set of extra disks by way of the `extra_worker_disks` _key_ in the clusters **KCLI parameter file**.
The `worker` nodes of course also gets a system disks. Normally this disk ends up getting the `sda` identifier. However, in some cases this isn't the case. And that causes issues when we e.g. bootstrap the extra disks for the intend we have for them. Namely acting as `JBOD's` for the storage pool to be consumed by the `CSI` `Longhorn`.

Here's an example of this happening: 

<img width="783" alt="Screenshot 2022-11-02 at 20 54 37" src="https://user-images.githubusercontent.com/5261530/199589611-5def495a-aff6-4bc1-a3f0-d52bb698fe6e.png">

---

How can we ensure that this doesn't happen? Looking through the code, with the caveat that I don't get everything, this doesn't look like KCLI/Pyvmomi specifically. I'm leaning towards this being an issue with the way that `Ubuntu 20.04` picks up the disks. But, before I dive into debugging `Ubuntu` on this issue - I would be very thankful if you give this a thought @karmab. Thank you very much.

**Comment by karmab** [comment]
as commented on slack, there's nothing in kcli forcing disk names, they just come from the OS

**Comment by larssb** [comment]
Is there something in the logic on the sys. disk and the extra disks are added to the vm ... e.g. if the code "waits" until the sys. disk is accepted and created before adding the extra worker disks - this might not happen? The downside to that is of course that it'll slow the bootstrapping process. I guess that could be acceptable.

**Comment by karmab** [comment]
no, the disks are created before the vm is actually launched
