### ISSUE TITLE
Default vars in /etc/kcli/config.yml (also global vars)

### ISSUE THREAD

**Issue by mperezco** [karmab/kcli#48]
Include a /etc/kcli/config.yml config file to have the default vars which will be global

**Comment by karmab** [comment]
i 'm still thinking whether it s needed

**Comment by mperezco** [comment]
It would provide a set of defaults in a place where users would go to look for.
It can also be then used as a template to be copied to user's home dir and used as users vars.

**Comment by karmab** [comment]
i think it s now addressed by the fact that an user can run kcli bootstrap and get default values visible in the resulting ~/.kcli/config.yml
the issue with /etc storing defaults was the use of container and running on macosx
