### ISSUE TITLE
qemu-system-x86 using ~13% CPU when guest idle

### ISSUE THREAD

**Issue by Ferni7** [karmab/kcli#489]
I ran up 2 ubuntu vms
```
kcli create vm -i ubuntu2004 vm1 -P nets=[br0]
kcli create vm -i ubuntu2004 vm2 -P nets=[br0]
```

I noticed that after startup, in the host the 2 qemu-system-x86 processes were using about 13% CPU each.

I edit vm1
`virsh edit vm1`
Remove lines 53-55
```
    <controller type='usb' index='0' model='piix3-uhci'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
```
and 81,82,83
```
    <input type='tablet' bus='usb'>
      <address type='usb' bus='0' port='1'/>
    </input>
```

Then restart the vm
```
kcli stop vm vm1
kcli start vm vm2
```

now cpu usage of vm1 is ~1% after removing the usb device, where as vm2 has ~13% still.

Is there a way I can disabled/remove the usb device from the guest with kcli create?

**Comment by karmab** [comment]
I think it's a fair assumption that 99% of the libvirt vms created with kcli don't need the benefit that using this tabled usb input brings so I removed it here https://github.com/karmab/kcli/commit/bbeb48575b07dbcb6b952cdb0d509e5fbd80fc00

thanks for the head up!

**Comment by Ferni7** [comment]
Perfect, just upgraded and tested, much better. Thank you sir.
