### ISSUE TITLE
Backingvolume is incorrectly determined when template is available in more than 1 pool

### ISSUE THREAD

**Issue by efenex** [karmab/kcli#5]
When a template is available in more than 1 pool, there is no guarantee the correct one is selected.

Example:

 LVM pool "hdd", LVM pool "ssd"
 Template "debian" is uploaded to both pools (in order to be able to spawn instances from either)

When creating a new VM, the following line:

 backing = backingvolume.path()

Always returns the "last" pool where the template is found. I believe the issue originates here:

        for p in conn.listStoragePools():
            poo = conn.storagePoolLookupByName(p)
            for vol in poo.listAllVolumes():
                print("looking up volume %s in pool %s: %s" % (vol,p,vol.path()))
                volumes[vol.name()] = {'pool': poo, 'object': vol}

Where volumes are distinguished by name only, and not pool (in the volumes dict). This means that a volume that exists in two pools with the same name is only available in this dict once, with whichever pool happens to have been processed last.

Workaround is to use either different names for templates in different pools (i.e. to add the pool-name into the template-name), or just make sure that a template is only available in 1 pool.

Ideally, kcli would use the pool path in the volumes dict as part of the key, i.e.:

                volumes["%s/%s" % (pool.name(),vol.name())] = {'pool': poo, 'object': vol}

This is not a minor change however, as this logic is used in several locations (and should be changed in all of them). Additionally, other code relies on the key-value to access the template information, and needs to be updated accordingly. It may be advisable to use a UUID rather than a string (i.e. the ones in /dev/disk/by-uuid/ ?) for the key value.

**Comment by karmab** [comment]
Yeah you re right, logic beeing that one would normally upload a given
template once.
When dealing with file based pools, you can easily deploy from templates
wherever this template is located. For lvm pools, you indeed need to access
the specific template within the same pool that your base disk.
I will correct the templates path gathering.
Let me know your progress on using the tool

**Comment by efenex** [comment]
Using the workaround described above, I've gotten my "plan" deployed successfully with all of the VM's we need. 

The ubuntu image deploys flawlessly, debian/archlinux seem to have issues (debian gives me connection resets on ssh attempt, archlinux doesn't seem to have the sshkeys deployed). Will have to look into the images for these.

Once these issues are resolved, next step will be toying around with the ansible-inventory module and working on setting up the VM's themselves.

**Comment by efenex** [comment]
debian (8.6) seems to be a cloud-init issue, ssh doesn't start because of it:

Oct 15 09:21:17 debian.example.com cloud-init[373]: [CLOUDINIT] util.py[WARNING]: No instance datasource found! Likely bad things to come!
Oct 15 09:21:17 debian.example.com cloud-init[371]: 2016-10-15 09:21:17,804 - DataSourceEc2.py[CRITICAL]: Giving up on md from ['http://169.254.169.254/2009-04-04/meta-data/instance-id'] after 120 seconds
Oct 15 09:21:17 debian.example.com cloud-init[371]: 2016-10-15 09:21:17,804 - util.py[WARNING]: No instance datasource found! Likely bad things to come!
Oct 15 09:21:17 debian.example.com cloud-init[373]: [CLOUDINIT] util.py[DEBUG]: No instance datasource found! Likely bad things to come!

**Comment by efenex** [comment]
same errors for archlinux (and some additional ones regarding netctl)

**Comment by karmab** [comment]
Oh it looks like both distribs configure cloudinit so it only tries to
contact network datasources and not cdroms one.
/etc/cloud/cloud.cfg can be tweaked on the image as a workaround but we
should report the issue to both distribs...

**Comment by efenex** [comment]
yeah just found out the same, issue is here in debian:

 /etc/cloud/cloud.cfg.d/90_dpkg.cfg

and here in archlinux:

 /etc/cloud/cloud.cfg.d/90_datasource.cfg

These files should include the "NoCloud" datasource. 

Just edited these manually and it works fine, so I'll guestfish the source images now and see if the whole flow works then.

**Comment by efenex** [comment]
Created an issue for the archlinux one here...

https://github.com/hartwork/image-bootstrap/issues/36

**Comment by efenex** [comment]
And reported the issue with the debian image on @ #debian-cd on the oftc/debian IRCd.

**Comment by karmab** [comment]
modified the code so that when a full  path is specified in the template directive, the corresponding backing template gets used

**Comment by efenex** [comment]
awesome!
