### ISSUE TITLE
Worker node's status becomes 'NotReady' after reboot, and does not automatically change to "Ready"

### ISSUE THREAD

**Issue by hj-johannes-lee** [karmab/kcli#505]
I created a cluster with "kcli create kube generic" with a parameter file.

After a cluster is configured with "kcli create kube generic" in one control plane and one worker node, if I reboot worker node then it becomes in "NotReady" status.

I set the 'engine' in the parameter file as 'crio' and found out that the cause is because "crio" does not start when the node gets rebooted. After starting 'crio' inside the worker vm, I can see the worker node's status becomes ready.

It would be good if the cluster configuration script includes setting crio to be one of 'startup' programs so that it can reboot after reboot.

I have not tested with containerd. Idk if it also has the same problem.

**Comment by karmab** [comment]
fixed by https://github.com/karmab/kcli/commit/497238370bc66997e581f6a3d58fdf7b3753d177
