### ISSUE TITLE
Add support to deploying k0s clusters

### ISSUE THREAD

**Issue by fidencio** [karmab/kcli#508]
In the same way where we have the support to deploy `k3s` clusters, we should consider adding support to deploying `k0s` clusters.

**Comment by fidencio** [comment]
Reference: https://docs.k0sproject.io/v1.23.6+k0s.2/install/

**Comment by karmab** [comment]
my take is to decide whether a given distrib needs to make its way in kcli base code.
For this, I generally base myself on popularity of the solution so question is whether k0s ( or rke2) are popular enough to justify the work

**Comment by fidencio** [comment]
@karmab, would be possible to re-open this one as we may work on / need this from the Kata Containers side, and it'd be good to have it opened for reference.
