### ISSUE TITLE
Ansible dynamic inventory klist.py is broken

### ISSUE THREAD

**Issue by jtudelag** [karmab/kcli#51]
The message "Using local hypervisor as kcli.yml wad found" should not be displayed, only the json.
Otherwise, it does not work as Ansible doesnt know how to parse it.

./klist.py --list                                      
**Using local hypervisor as no kcli.yml was found...**
{"kvirt": {"hosts": ["ansible-graph", "minishift"], "vars": {"profile": "", "plan": "kvirt"}}, "_meta": {"hostvars": {"ocp-infra": {"status": "up", "ansible_host": "192.168.122.15", "ansible_user": "cloud-user"}, "ocp-node": {"status": "up", "ansible_host": "192.168.122.224", "ansible_user": "cloud-user"}, "minishift": {"status": "down"}, "ansible-graph": {"status": "up", "ansible_host": "192.168.122.43"}, "ocp-master": {"status": "up", "ansible_host": "192.168.122.40", "ansible_user": "cloud-user"}}}, "ocp-lab": {"hosts": ["ocp-master", "ocp-infra", "ocp-node"], "vars": {"profile": "rhel73_medium", "plan": "ocp-lab"}}}

**Comment by karmab** [comment]
fixed in 7.19
