### ISSUE TITLE
kcli no longer uses openshift-install available in path

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#516]
In the latest versions, kcli insists in dowloading the openshift-install binary instead of using the one in the path.

**Comment by karmab** [comment]
I think I've fixed it here https://github.com/karmab/kcli/commit/c599c531be433038c528021df641ccf27fc0b9b9
(it has the benefit of only using the binary, whether from existing path or from current directory, if it matches target version)

**Comment by karmab** [comment]
no, you should be able to keep whatever tag you were using

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/782f785197810c55f012bf91b5e016c1a0c3e9e7
