### ISSUE TITLE
Multi-lines cmds break ssh access to the VM

### ISSUE THREAD

**Issue by josecastillolema** [karmab/kcli#522]
For some reason, multi-line cmds break ssh access to the VM:
```
$ cat .kcli/plans/kcli-plans/fedora_kubemark.yml
parameters:
  image: Fedora-Cloud-Base-37-1.7.x86_64.qcow2
fedora_kubemark:
  image: {{ image }}
  cmds:
    - |
      cat <<EOF >> /home/fedora/clusterctl-settings.json
      {
          "providers": ["cluster-api", "bootstrap-kubeadm", "control-plane-kubeadm", "infrastructure-docker", "infrastructure-kubemark"],
          "provider_repos": ["../cluster-api-provider-kubemark"]
      }
      EOF

$ kcli product create fedora_kubemark

$ kcli ssh fedora_kubemark
fedora@192.168.122.252: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

Have tried `- >` as well as multi-line separator with same results.

**Comment by karmab** [comment]
yes, sadly, commands with the : sign easily break cloudinit injection so when you want to use something like this, it's better to use a file key to inject a script and then run it

fedora_kubemark:
  image: {{ image }}
  files:
    path: /home/fedora/clusterctl-settings.json
    content: |
       {
          "providers": ["cluster-api", "bootstrap-kubeadm", "control-plane-kubeadm", "infrastructure-docker", "infrastructure-kubemark"],
          "provider_repos": ["../cluster-api-provider-kubemark"]
       }
