### ISSUE TITLE
problem determining whether libvirt is up preventing kcli from working

### ISSUE THREAD

**Issue by pcuzner** [karmab/kcli#523]
On F37 I couldn't get kcli to work even though libvirt was present and started.
paul@T15Gen2:~/Documents/OpenShift/sno-vm$ sudo kcli list vm 
No configuration found nor local hypervisor. Is libvirt running?

When I looked at the check  at https://github.com/karmab/kcli/blob/4885c594410ae202abc2047972e9e6ec85337855/kvirt/baseconfig.py#L100 it's looking for libvirt-sock, but on my system there are two socket files libvirt-admin-sock and libvirt-sock-ro. I created a symlink to the admin socket to test, and now kcli is happy again.

My versions are 
kcli-99.0.0.git.202303291230.4885c59-0.fc37.x86_64
libvirt-daemon-8.6.0-5.fc37.x86_64

**Comment by karmab** [comment]
Thanks for the report!
This should be addressed in https://github.com/karmab/kcli/commit/758a8f161dc98dcab1f655ebb61fdfa581f91c34
This comes from the refactoring done in libvirtd to separate the daemon into multiple components
Note you shoulnt use sudo to run kcli, but instead add your user to libvirt group, as indicated in https://kcli.readthedocs.io/en/latest/#libvirt-hypervisor-requisites
