### ISSUE TITLE
RHCOS images name collision

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#532]
Recently, most (if not all) the RHCOS images are named like this:
```
https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/latest/rhcos-openstack.x86_64.qcow2.gz
```
i.e. the name no longer contains the version.

So imagine the following sequence:
- You run `kcli download image rhcos412`
- It downloads `https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/latest/rhcos-openstack.x86_64.qcow2.gz` to `/var/lib/libvirt/images/rhcos-openstack.x86_64.qcow2`
- Right after that, you run `kcli download image rhcos411`
- It would download `https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.11/latest/rhcos-openstack.x86_64.qcow2.gz` to `/var/lib/libvirt/images/rhcos-openstack.x86_64.qcow2` but there is already a `/var/lib/libvirt/images/rhcos-openstack.x86_64.qcow2` file, so kcli mistakenly believes that the image is already downloaded.

The only solution that would come to my head would be automatic renaming of the qcow2 file, to add the OCP version (at least, that's what I do manually, by renaming the file).

**Comment by karmab** [comment]
addressed using your suggestion through https://github.com/karmab/kcli/commit/2a522ba0881af327b7a95b336614231023111b99

**Comment by palonsoro** [comment]
Thx!
