### ISSUE TITLE
OCP4 won't install in KVM with the openstack images

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#536]
Since today, whenever I try to install OCP4 on KVM with kcli, as usual, it never ends because the VMs try to get ignition from OSP metadata endpoint and that fails. It seems that they don't try to get ignition from QEMU `-fw_config` option.

Important remarks:
- I am aware that openstack images used to work since long. I am surprised that now they don't.
- I have not updated any RPM other than kcli.
- The VMs are created with the right `-fw_config` setting as per `virsh dumpxml` output
- I have even tried with older versions of kcli that used to work and now they don't work as well. It is very possible that something just changed in the RHCOS images.
- A valid workaround is to manually download the QEMU qcow2 images and use them instead of openstack ones. This ones do obey `-fw_config` setting.

So not sure if I may be doing something wrong or they made a breaking change. Maybe the solution is as simple as switching to QEMU images on KVM, maybe there is something wrong more that needs troubleshooting.

**Comment by palonsoro** [comment]
Another important note: unlike other VMs I have around, the OCP4 VMs don't get an ISO created for a config drive. Maybe that's the ultimate root cause of the issue.

**Comment by karmab** [comment]
fixed [here](https://github.com/karmab/kcli/commit/f169597a799b7d474303ea82225226c1ef7d7e0b)
