### ISSUE TITLE
Funny workflow runs in fork repo are back

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#537]
I have recently started having an issue similar to what was reported in https://github.com/karmab/kcli/issues/348 

GitHub tries from time to time to schedule and run actions on my fork of kcli that should be run only for the main repo.

**Comment by karmab** [comment]
can you provide an example so that I locate which workflow lacks the correct filtering?

**Comment by palonsoro** [comment]
The ones for which I received recent frequent e-mails:
- KUBEADM-NIGHTLY-CI
- HYPERSHIFT-ASSISTED-NIGHTLY-CI
- HYPERSHIFT-NIGHTLY-CI
- SNO-NIGHTLY-CI

**Comment by karmab** [comment]
should be fixed by https://github.com/karmab/kcli/commit/71304234f34cd50dc47282e7af55e0a405d12b1d
