### ISSUE TITLE
Creating OCP4 cluster without "image" parameter re-downloads the image with different name

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#538]
Basically, if I create an OCP4 cluster without explicitly specifying the `image:` parameter, the following happens:
```
$ kcli list image
+----------------------------------------------------------------------------+
| Images                                                                     |
+----------------------------------------------------------------------------+
| /var/lib/libvirt/images/centos9stream                                      |
| /var/lib/libvirt/images/rhcos410                                           |
| /var/lib/libvirt/images/rhcos412                                           |
| /var/lib/libvirt/images/rhel-server-7.9-update-12-x86_64-kvm.qcow2         |
+----------------------------------------------------------------------------+

$ kcli create kube openshift --paramfile ./parameters-leeloo-ovn-4.10.yml -P tag=4.10.50 leeloo                                                                                                                
Deploying on client local
Deploying cluster leeloo
Using stable version
Using existing openshift-install found in your PATH
Using installer version 4.10.50
Grabbing image rhcos-410.84.202210040010-0-openstack.x86_64.qcow2 from url https://rhcos.mirror.openshift.com/art/storage/releases/rhcos-4.10/410.84.202210040010-0/x86_64/rhcos-410.84.202210040010-0-openstack.x86_64.qcow2.gz             
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  987M  100  987M    0     0   104M      0  0:00:09  0:00:09 --:--:--  109M
Image rhcos-410.84.202210040010-0-openstack.x86_64.qcow2 Added
Using image rhcos-410.84.202210040010-0-openstack.x86_64.qcow2
INFO Consuming Install Config from target directory
(...)

$ kcli list image
+----------------------------------------------------------------------------+
| Images                                                                     |
+----------------------------------------------------------------------------+
| /var/lib/libvirt/images/centos9stream                                      |
| /var/lib/libvirt/images/rhcos-410.84.202210040010-0-openstack.x86_64.qcow2 |
| /var/lib/libvirt/images/rhcos410                                           |
| /var/lib/libvirt/images/rhcos412                                           |
| /var/lib/libvirt/images/rhel-server-7.9-update-12-x86_64-kvm.qcow2         |
+----------------------------------------------------------------------------+
```

It downloads again the image with a name that does not follow the current naming pattern (see https://github.com/karmab/kcli/issues/534) instead of detecting the already present one.

**Comment by karmab** [comment]
this is the intended behaviour:
the image to use is evaluated using `openshift-install coreos print-stream-json` and only downloaded if not present.

So, in your example, although you have a rhcos410 image, it might not be the one associated to this version of the installer

Note that, luckily, those images don't get rebased too often during a version lifecycle but not specifying the image prevents mismatches (that might happen precisely when such rebases happen)

**Comment by palonsoro** [comment]
Hi,

Actually it is the same image:
```
$ md5sum /var/lib/libvirt/images/rhcos410 /var/lib/libvirt/images/rhcos-410.84.202210040010-0-openstack.x86_64.qcow2 
76c4548d596d320da6af38e6e235ca40  /var/lib/libvirt/images/rhcos410
76c4548d596d320da6af38e6e235ca40  /var/lib/libvirt/images/rhcos-410.84.202210040010-0-openstack.x86_64.qcow2
```

Besides, RHCOS images may change more often than you think: Not all the different RHCOS versions are published for installation at https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.10/ (or similar) but only when they have fixes or improvements relevant for the installation. This is because nodes are later pivoted to the right version, so it is usually not required to be so careful with the base image. However, with the current approach, each different RHCOS version for each different 4.10.z version will be downloaded (because they are available, just elsewhere), which may result in more different RHCOS images for the same 4.y donwloaded as one would initially expect.

If this is still expected behavior, that's fine to me. I'll just add the `image:` parameter back :slightly_smiling_face:

**Comment by karmab** [comment]
yes force the image, (since using the associated image to a given build is the recommended workflow from Openshift Documentation)

**Comment by palonsoro** [comment]
Actually, openshift-docs only require the same 4.y, but that's fine (in fact, it is more important that the image is always the one used to install the cluster, but... not relevant).
