### ISSUE TITLE
Baremetal installs should error out early if virtual ISO cannot be mounted

### ISSUE THREAD

**Issue by lack** [karmab/kcli#539]
When creating an SNO OpenShift cluster with `sno_wait: true`, I sometimes get the following error:

```
Booting Host with url sno-6.bmc.platform.bos2.lab with http://192.168.20.11/sno-6-sno.iso
Hit HTTP Error 500: Internal Server Error when plugging iso to host with url sno-6.bmc.platform.bos2.lab
Launching install-complete step. It will be retried extra times in case of timeouts
INFO Waiting up to 40m0s (until 10:01AM) for the cluster at https://api.sno-6.platform.bos2.lab:6443 to initialize... 
```

If the ISO fails to mount, we should exit immediately and not wait for the installation to complete.

In the case of 401 errors (if I have the wrong BMC credentials), it should exit immediately.

In the case of 500 errors (which seem intermittent depending on the BMC software), we could even retry a few times but still give up if it wasn't eventually successful.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/70d8ba3a897211b66667cd979d565a5f26123dfc
