### ISSUE TITLE
kcli -C all list outputs traceback

### ISSUE THREAD

**Issue by likid0** [karmab/kcli#54]
Using kcli version 7.20, kcli list output is displayed ok, but it outputs a traceback at the end of the command:

~> kcli -C all list
+-----------------------+---------------+--------+-----------------+----------------------------------------------+------------------+---------------+--------+
|          Name         |      Host     | Status |       Ips       |                    Source                    | Description/Plan |    Profile    | Report |
+-----------------------+---------------+--------+-----------------+----------------------------------------------+-----------
...............
...................
|        liberty        | openstackbox2 |   up   |                 | rhel-guest-image-7.2-20160302.0.x86_64.qcow2 |     liberty      |     kvirt     |        |
+-----------------------+---------------+--------+-----------------+----------------------------------------------+------------------+---------------+--------+

Traceback (most recent call last):
  File "/usr/bin/kcli", line 9, in <module>
    load_entry_point('kcli==7.20', 'console_scripts', 'kcli')()
  File "/usr/lib/python2.7/site-packages/kvirt/cli.py", line 890, in cli
    config.k.close()
AttributeError: Kconfig instance has no attribute 'k'

**Comment by karmab** [comment]
fixed in 
https://github.com/karmab/kcli/commit/d756b30185d483b10867564a6265520e061c5e13
