### ISSUE TITLE
Add support to provide plan files when create kubernetes/openshift clusters

### ISSUE THREAD

**Issue by zaskan** [karmab/kcli#540]
As far as I can see, currently is not possible to specify a plan file when deploying kubernetes or openshift clusters. (kcli create cluster)
It could be great since it would grant the user to configure specific options per vm that are not possible using the command above.

**Comment by karmab** [comment]
I think you mean a parameter file but you can certainly provide one when creating a cluster

```
kcli create cluster kubeadm --pf your_param_file
```

to know which parameters are available, use `kcli info cluster kubeadm`

note that not all kcli keywords show as available but if you have a need for something specific for a single or group of vms, you can specify vmrules in your parameter file
