### ISSUE TITLE
[GCP Provider] Somewhat weird output when deploying again after a previously failed deploy

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#546]
I'm seeing

![image](https://github.com/karmab/kcli/assets/80959443/632e3756-d990-435b-8243-e7a2a4eeb90a)

when trying to deploy again after a failed deploy.

The line: `Deleting loadbalancer api.gcp-test`

- I haven't been able to find any load balancer actually created under the project or other projects on our account
- Was it registered in the local KCLI cache

I think the output/message is somewhat misleading. Would be great to not have it - unless there's actually good reasoning behind it.

N.B. this is on `kcli version` = **version: 99.0 commit: 708952e 2023/05/15 Available Updates: False**

**Comment by LarsBingBong** [comment]
Still get the `Deleting loadbalancer api.gcp-test` output. Also in the case where there's no resources deployed at all in the `Project` on the `Google Cloud Compute Engine` offering.

**Comment by larssb** [comment]
Yeah this is still an issue,

**Comment by LarsBingBong** [comment]
Is it fixable?
