### ISSUE TITLE
[GCP Provider] The same SSH key is duplicated on VM's deployed

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#561]
This is an issue/annoyance when e.g. editing X VM deployed via KCLI on GCP.

The Google Cloud Console will complain with:

![image](https://github.com/karmab/kcli/assets/80959443/9bb0689f-e485-4377-9359-994fc4fc4ab0)

The you click _issues_  and get to:

![image](https://github.com/karmab/kcli/assets/80959443/5a278be3-e3b3-4d5c-96c4-4579a9655fe8)

---

This can easily be worked around by "just" deleting one of the duplicated SSH key and then hitting save.

However, it would save time and be nice if this wasn't needed.

Thank you very munchies.

**Comment by karmab** [comment]
I believe this is a bug in GCP UI, cos those keys are not duplicate, they are associated to different users (your regular one and root when enableroot is set, as it is in the k3s workflow)

**Comment by LarsBingBong** [comment]
Yeah it might be. The cause could be that GCP doesn't like that it's the exact same key. Or actually, Google Cloud seems to derive the username from the my-username@device-name if it's appearing in the SSH public key. As that's also a thing I bumped into. If I edit the VM, the GCP consule complains about the ssh keys section >> I have to remember to change the username of the ssh-key if it appears in the key field.

... I guess I might as well remove the username from the ssh-key ... and then see what the result is.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/0ccb8e18a48edd1e52b95047814ebb14a28c8938
there's no need to populate the key for the root user as GCP data since we do it at cloudinit level
