### ISSUE TITLE
kcli cannot generate kube

### ISSUE THREAD

**Issue by pikapi111** [karmab/kcli#563]
`[root@master .kcli]# kcli create kube generic -P image=ubuntu2004 testk8s
Using 192.168.122.253 as api_ip
Using keepalived virtual_router_id 184
Downloading kubectl in current directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46.9M  100 46.9M    0     0  2819k      0  0:00:17  0:00:17 --:--:-- 3607k
Deploying Vms...
No acceleration available with this hypervisor
Waiting for vm testk8s-ctlplane-0 to finish customisation
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...`
how should i solve this problem？

**Comment by karmab** [comment]
hello!
I think the message "No acceleration available with this hypervisor" means that you're either:
- running on a box which lacks accelerated virtualization 
- doing nested virtualization withoout enabling nested in kvm_intel module

so that's what needs to be fixed

**Comment by pikapi111** [comment]
Thank you very much for your help, I turned on the virtualization of the VM and that worked. But a new problem appeared, and the following problem occurred during installation.
`Setting up ipvsadm (1:1.31-1) ...
Setting up keepalived (1:2.0.19-2ubuntu0.2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/keepalived.service → /lib/systemd/system/keepalived.service.

scp: /etc/kubernetes/admin.conf: No such file or directory
peer-pods-ctlplane-0 deployed on local
Deploying workers
Deploying Vms...
peer-pods-worker-0 deployed on local
Kubernetes cluster peer-pods deployed!!!
INFO export KUBECONFIG=$HOME/.kcli/clusters/peer-pods/auth/kubeconfig
INFO export PATH=$PWD:$PATH
Adding app ingress
W0604 11:25:38.088350    4187 loader.go:222] Config not found: /root/.kcli/clusters/peer-pods/auth/kubeconfig
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Wait at least one worker be Ready
W0604 11:25:38.170616    4195 loader.go:222] Config not found: /root/.kcli/clusters/peer-pods/auth/kubeconfig
E0604 11:25:38.171640    4195 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0604 11:25:38.171855    4195 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0604 11:25:38.173175    4195 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0604 11:25:38.174666    4195 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0604 11:25:38.176271    4195 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused`
Because there is no /etc/kubernetes/admin.conf file? 
Do I need to create this file myself?

**Comment by pikapi111** [comment]
I also found some other problems
`ssh: connect to host 192.168.122.180 port 22: Connection refused
Gathered ip not functional yet...
Waiting for vm to be accessible...
ssh: connect to host 192.168.122.180 port 22: Connection refused
Gathered ip not functional yet...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
`

**Comment by karmab** [comment]
can you provide the full output of the run and confirm you re using kvm as hypervisor?

**Comment by pikapi111** [comment]
[que.md](https://github.com/karmab/kcli/files/11645238/que.md)
Thank you very much, I have shown all the output in the document.
I am currently using your kcli in the linux system built by VMware under the windows10 system.
I'm a newbie, don't know if this is possible.

**Comment by karmab** [comment]
the issue seems to be the following

```
 Could not connect to packages.cloud.google.com:443 (142.251.43.14). - connect (111: Connection refused)
Reading package lists...
W: Failed to fetch http://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  Could not connect to packages.cloud.google.com:443 (142.251.43.14). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

So for whatever reason, the first ctlplane vm (which acts as bootstrap one) cant get the metadata for the kubernetes repo.
Seems like a network connectivy issue in your hypervisor setup

**Comment by pikapi111** [comment]
Thank you for your help. I also found this problem. I set up a proxy for the Linux virtual machine. I can access Google in my browser. I don't know why the connection fails here. May I ask how I can solve this problem? Thank you again for your reply.

**Comment by karmab** [comment]
try setting the parameter HTTP_PROXY

**Comment by pikapi111** [comment]
I configured http_proxy and still couldn't create a kube cluster directly with instructions (probably because I didn't configure it successfully). I have a new idea to use kcli to achieve the same result as the instruction. I can use kcli to create two virtual machines, then modify their download sources to install the Kubernetes components, and then use kcli to synthesize them into kube. Can this bypass the download failure problem and achieve the same result?

**Comment by karmab** [comment]
Hello, I dont think you should need to create single vms and provision kube by yourself, but feel free to do that for debugging purposes

**Comment by karmab** [comment]
closing as it seems to be an environmental/networking issue.
Feel free to ping me on slack so we can debug your env live
