### ISSUE TITLE
[GCP Provider] KCLI not deleting load balancers created after bootstrapping

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#569]
This is totally an open discussion. As it's totally fair, with the current state _knowledge_ that `KCLI` have on a K8s cluster it bootstrapped. As it no nothing about load balancers created on `GCP` after bootstrapping the cluster. Especially not when this is done with the `cloud-controller-manager`.

Anyways. Let's give this a look....

![image](https://github.com/karmab/kcli/assets/80959443/c9922940-a90e-48e7-b48b-9ff1f83e1ed6)

---

As if one have several cluster it can be quite _hard_ to figure out what load balancer belongs to what cluster. And it's just an annoying tedious extra task after having deleted a cluster.

What do you think - is this something KCLI could handle within a reasonable scope? Thanks

**Comment by karmab** [comment]
kcli's philosophy is to delete only the resources it owns and for that, tagging is used.
In the case of loadbalancers, we are able to delete them when a vm has a loadbalancer metadata/tag
As long as you tag one of the vms with your loadbalancer name, it will be deleted along with vm

**Comment by LarsBingBong** [comment]
Hmm I like the suggesting. Would be great to be able to delete load balancers based on specific tags. However, tagging VM's as load balancer are deployed with the cloud-controller-manager is an involved flow. Because:

- We can't really control the CCM code
- There doesn't seem to be a way by which one can, e.g. via an annotation or label on a `Kind: Service` object communicate to the CCM that a load balancer creates should have a certain tag

---

We might "just" have to wrap the call to `kcli --client GCP_RELATED_CLIENT delete cluster CLUSTER_NAME` so that a `Kind: Service, type: Loadbalancer` `Services` are deleted ... so that the CCM call the proper GCP API's to get these load balancers deleted.

**Comment by larssb** [comment]
I ended up wrapping up KCLI sp that load balancer type services are deleted before the call to kcli delete cluster.

**Comment by LarsBingBong** [comment]
....
