### ISSUE TITLE
what's the difference between parameter file and plan file?

### ISSUE THREAD

**Issue by bayeslearner** [karmab/kcli#577]
```
parameters:
    cluster1_ctlplanes: 1
    cluster1_workers: 1

k8s-net:
    type: network
    cidr: 192.168.95.0/24

cluster1:
    type: kube
    ctlplanes: {{ cluster1_ctlplanes }}
    workers: {{ cluster1_workers }}
    cluster: mycluser
    domain: bayeslearner.org
    network: k8s-net
```

Given the above file inspired from your samples repo,  I ran:
```
kcli create plan -f kcli_plan.yml
```

but I got 
```
Using agitated-joerobinson as name of the plan
Deploying Networks...
Network k8s-net skipped!
Deploying Kube Entries...
Deploying Cluster cluster1...
```
There is nothing more, no errors, no outputs. 

I then ran:
```
$ kcli list clusters
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3/dist-packages/kvirt/cli.py", line 5165, in cli
    args.func(args)
  File "/usr/lib/python3/dist-packages/kvirt/cli.py", line 1368, in list_cluster
    kubes = config.list_kubes()
  File "/usr/lib/python3/dist-packages/kvirt/config.py", line 1254, in list_kubes
    for kube in next(os.walk(clustersdir))[1]:
StopIteration
```

I also saw this command in your doc.  I'm quite confused. 
```
kcli create kube generic --paramfile <parameters file>
```

Also I'm running this on a ubuntu desktop with libvirt enabled.  Does the base system have to be a redhat?

**Comment by karmab** [comment]
I think it's worth a dedicated section in the doc, so I'll add it but let me address your concerns here (in reverse order):

- base system doesnt have to be rhel based. Any local (or remote) hypervisor should work
- kcli has the ability to create not only vms, but other objects such as network or kubernetes clusters. Such objects can either be created using a dedicated command (think kcli create vm or kcli create cluster) or they can be combined in a yaml file, that's what a plan is.
- when you create a kcli object, you can provide parameters at run time, either using the syntax -P key=value in a repeated way, or by providing a dedicated yaml file with those parameters, that's what a parameter file is.
- The plan file is actually a jinja file so you can use loops or conditionals there, and use the keys from the parameters section of the file
- the parameters section that are the top of your sample plan can also go in a dedicated file, typically named $plan_default.yml, kcli_plan_default.yml or kcli_default.yml. Note that it's also a parameter file but with a different purpose, providing default parameter values.
- 
Let me know if it helps

**Comment by karmab** [comment]
regarding the list cluster failure, it was caused by the fact that you didnt have any installed cluster and as such didnt have any clusterdir. I fixed it in https://github.com/karmab/kcli/commit/f9410e37668df7e12ed45d091d43735e21361bca

**Comment by bayeslearner** [comment]
The "full" output of kcli list cluster is what I gave above.  Nothing else. 

So why didn't my plan work?  It created the network (thus the skipping upon second run) but it didn't start creating VMs and K8s.

**Comment by karmab** [comment]
its weird indeed, the plan in my case produces the following output

```
Using lonely-fusilijerri as name of the plan
Deploying Networks...
Network  k8s-net deployed
Deploying Kube Entries...
Deploying Cluster cluster1...
Using 192.168.95.253 as api_ip
Using keepalived virtual_router_id 131
Deploying Vms...
Waiting for vm cluster1-ctlplane-0 to finish customisation
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
Waiting for vm to be accessible...
(...)
```

**Comment by karmab** [comment]
worth troubleshooting live on your env, please ping on slack?

**Comment by bayeslearner** [comment]
> worth troubleshooting live on your env, please ping on slack?

How do I get to your slack workspace? I clicked on the slack link but it asked me to create new slack workspace, instead of signing me in.

**Comment by karmab** [comment]
if you have a ssh key in .ssh, that works too
