### ISSUE TITLE
[FEATURE REQUEST] - Have KCLI handle the prerequisites it needs for different tasks.

### ISSUE THREAD

**Issue by LarsBingBong** [karmab/kcli#578]
So e.g. when using the `KCLI` `GCP` provider one needs to install:

```bash
pip3 install google-api-python-client google-auth-httplib2 google-cloud-dns
pip3 install python-dateutil
pip3 install google-cloud-storage
pip3 install google-cloud-container
```

However, one do **NOT** find out before having run into an error when `KCLI` tries to do xyz. But, fails because it's missing a prerequisite.

I think it would be great if `KCLI` handles the prerequisites it needs.

- Better user experience
- Built-in and of you go when using `KCLI`

Thanks

**Comment by karmab** [comment]
- all the dependencies are installed in the container version
- the rpm or deb only provide libvirt
- for the other providers, rpm dependencies are indicated if they exist otherwise pip is mentioned

**Comment by karmab** [comment]
i agree though that a better user experience is to capture such errors and point to the doc.
So I added that in https://github.com/karmab/kcli/commit/82bee1c08c4c076160de4edaa657332a4d7569cd

**Comment by LarsBingBong** [comment]
Sure helps. Would be lovely still to have KCLI install the needed dependencies if not found. Or alternatively provide some automation for this in the case that any deps are not installed.

But, you don't want that added or do not think it's the responsibility of KCLI?

**Comment by karmab** [comment]
a bit ugly but here's a try to address it https://github.com/karmab/kcli/commit/75c711467aa353b4b93c0269f6f7202774add139

by adding `kcli install provider $provider`

What I dont like is that it uses pip for some of the providers, but that's the only way to get the dependencies in place.

Let me know if this addresses your need and I ll close

**Comment by LarsBingBong** [comment]
It certainly simplifies things for the end-user drastically. I think that part of it is wonderful. I can see why you're not loving the needed code. That can always be polished as we go along. However, for now it's great. I'll test it and push it into our docs. I think we're good for now if you can hit the `kcli install provider PROVIDER_X` command and it's working on your machine.

I think that for KCLI to expect python and pip to be available is okay. That's a chicken and egg kinda problem and in this case the chicken ( Python and pip ) should come first.

Thanks!
