### ISSUE TITLE
Is there a way to specify the plan name in plan.yaml?

### ISSUE THREAD

**Issue by ferni7** [karmab/kcli#589]
I can name the plan by specifying the name on the CLI like this:

`kcli create plan -f lab2-cluster.yaml lab2`

But is there a way I can specify the plan name in the lab2-cluster.yaml itself? (I couldn't find it in the docs)

**Comment by mvazquezc** [comment]
@ferni7 you can use the `plan` parameter. In your lab2-cluster.yaml put this:

~~~yaml
plan: lab2
~~~

**Comment by ferni7** [comment]
Thank you!
