### ISSUE TITLE
Fail to create kube if name has "_" underscore

### ISSUE THREAD

**Issue by wainersm** [karmab/kcli#596]
I was struggling to get a Kubernetes cluster created because I had "_"  underscore in its name (e.g `kata_k8s`). Only after I changed to `kata-k8s` it got created correctly. Apparently it failed to join the worker node into the cluster (the control and worker VMs were created).

The version I am using on a Fedora 36 x86_64 machine:
```
$ kcli version
version: 99.0 commit: e064fb4 2023/05/22 Available Updates: True
```

**Comment by karmab** [comment]
It indeed needs to be forbidden, so I did so in https://github.com/karmab/kcli/commit/f399f7f2b28d264bfa7bed993bb256b4d7e7503a
