### ISSUE TITLE
sharedkeys files are not deleted when the plan is deleted

### ISSUE THREAD

**Issue by jtudelag** [karmab/kcli#61]
When one of the vms in the plan has the property  
> sharedkey: True

, and the plan is deleted, the files *.key and *.key.pub are not deleted.

These files are stored in the plan file folder.

**Comment by karmab** [comment]
valid point

**Comment by karmab** [comment]
addressed in 5ec7855fbe7084acdf0bb5de920829ee16732676 by actually deleting both private and public key during the provisioning phase, as those are rather used by the vms and not that much from the machine running kcli ( user s own pub key is injected anyway, along with any extra pub keys specified in the keys array)
