### ISSUE TITLE
Failed when trying to use kcli create k8s cluster on Arm64 platform

### ISSUE THREAD

**Issue by zhlhahaha** [karmab/kcli#610]
Hi, I tried to use kcli to build k8s cluste on a Arm64 server (baremetal) but failed with following messages:
```
test-ctlplane-0 not deployed because unsupported configuration: Maximum CPUs greater than specified machine type limit
The following vms failed: test-ctlplane-0
```

My test script is:
```
kcli download image -u https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-arm64.img ubuntu2004

kcli -D create kube generic -P domain=test -P pool=default -P ctlplanes=1 -P workers=1 -P network=default -P image=ubuntu2004 -P sdn=flannel -P nfs=false -P disk_size=20 -P version=1.26.7 test
```

I conducted some investigation, and it appears that kcli is selecting the `raspi0` machine type based on the first entry in libvirt capabilities. This machine type has a maxCpus value of 1, while the default CPU count for the test-ctlplane virtual machine is 4. This leads to the error.

```
  <guest>
    <os_type>hvm</os_type>
    <arch name='aarch64'>
      <wordsize>64</wordsize>
      <emulator>/usr/bin/qemu-system-aarch64</emulator>
      <machine maxCpus='1'>raspi0</machine>
      <machine maxCpus='512'>virt-4.0</machine>
      <machine maxCpus='2'>mcimx7d-sabre</machine>
      <machine maxCpus='1'>imx25-pdk</machine>
      <machine maxCpus='2'>npcm750-evb</machine>
```

I didn't find any parameter in `kcli -D create kube generic` that allows you to set up the machine type (fix me if I am wrong). It might be beneficial to add a parameter that lets users specify the machine type they want when creating k8s cluster. Alternatively, setting the default machine type to `virt` on Arm64 can be a reasonable solution to ensure compatibility with the default CPU count.

**Comment by karmab** [comment]
you can specify machine as parameter and set it to one of the different types.
The code should pick the entry with virt preferently or at least the best entry cpu and memory wise so i ll have a look at that (on sunday)
