### ISSUE TITLE
ARM64 Image Support?

### ISSUE THREAD

**Issue by dronenb** [karmab/kcli#613]
Hi,

Thanks for creating such a cool project. Would it be possible to create a multi-arch container image for `kcli`? That way deployments could be made from Raspberry Pi, Apple Silicon computers, etc.

How to build multi-arch images with Podman: https://medium.com/oracledevs/building-multi-architecture-containers-on-oci-with-podman-67d49a8b965e

**Comment by karmab** [comment]
let me revisit, cos I know at some point I almost enabled multiarch in the CI

**Comment by karmab** [comment]
time to make this happen

**Comment by karmab** [comment]
sorry for the delay!
I ve pushed a multi arch image at quay.io/karmab/kcli:multi (on top of commit b35d41064c1d8d693694bed1b0469137a62b233e)
