### ISSUE TITLE
Install containerd from Ubuntu's distro on kube generic

### ISSUE THREAD

**Issue by wainersm** [karmab/kcli#619]
In https://github.com/karmab/kcli/issues/615 I was trying to create a kube generic cluster with Ubuntu 22.04. With the fix provided I am able to do that but then I hit another issue. Ubuntu 22.04 distributes containerd version 1.7, whereas on the kcli cluster it got installed 1.6. I suspect kcli has installed the Docker's provided package of containerd.

Why is kcli installing docker in the nodes?

Is there a way to instruct to install containerd from Ubuntu's distro instead of Docker's?

**Comment by karmab** [comment]
no, we default to installing containerd.io, I think docker is not even supported at this point for kubeadm

**Comment by karmab** [comment]
The official kubeadm doc points at using the docker repo for getting containerd although you're rigtht that ubuntu seems to provided it, at least for 22.4, but it s 1.6 anyway https://packages.ubuntu.com/jammy/admin/containerd

**Comment by wainersm** [comment]
hey @karmab , thanks for the prompt answer!

> The official kubeadm doc points at using the docker repo for getting containerd although you're rigtht that ubuntu seems to provided it, at least for 22.4, but it s 1.6 anyway https://packages.ubuntu.com/jammy/admin/containerd

The 1.7 version is available on jammy-updates repo: https://packages.ubuntu.com/jammy-updates/containerd

There is a couple of projects that I am working on that relies on kcli for building test environments, but we bumped the containerd version required to 1.7. I'm looking for ways to stick with kcli, that's why I asked if there is an alternative way to install the distro's containerd (hopefully the latest and greatest version).

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/9aa0ea9e93cd768adeef7493697d2741fb9092ff
