### ISSUE TITLE
Unable to create centos9stream kube

### ISSUE THREAD

**Issue by ldoktor** [karmab/kcli#624]
running `kcli create kube generic -P domain="example.com" -P pool=default -P ctlplanes=1 -P workers=1 -P network=default -P image=centos9stream -P sdn=flannel -P nfs=false -P disk_size=40 -P memory=16384 mycluster` fails to setup the cluster while everything works well on ubuntu as well as centos8stream. It looks like kubernetes issue since it works well when I manually set the kubernetes version to 1.23.17, but all newer versions fail to init (created issue here https://github.com/kubernetes/kubernetes/issues/122084 )

Anyway perhaps some setup change can be performed on kcli side to avoid this failure.

Note the output of kcli does not indicate the `kubeadm init` issue but it silently ignores it and finish complaining about uninitialized cni. Please find the full log attached.
[job.log](https://github.com/karmab/kcli/files/13486257/job.log)

**Comment by karmab** [comment]
the issue seems to be that the vip we use is not "registered" for use in the cluster, looks like something new

**Comment by karmab** [comment]
actually this rather looks like a kube issue, kube-apiserver isnt fully ready after kubeadm finishes, so the addon phase fails

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/16d424a4a497adcf545ac64e07a0ff74d1a14ec2

**Comment by ldoktor** [comment]
Thank you, Karim, it works well now
