### ISSUE TITLE
Failed to create VM with FileNotFoundError for .ISO in /tmp directory

### ISSUE THREAD

**Issue by cmaf** [karmab/kcli#626]
I tested on both Ubuntu 20.04 and 22.04 hosts, installed with the generic script and the prerequisites `libvirt-daemon-driver-qemu qemu-kvm`, with the default pool set to `/var/lib/libvirt/images`. Upon creating a VM, the following error occurs:

```
$ kcli create vm -i ubuntu2204 -P disks=[20] -P numcpus=2 -P memory=2048 test-1

Deploying vm test-1 from image ubuntu2204...
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3/dist-packages/kvirt/cli.py", line 5364, in cli
    args.func(args)
  File "/usr/lib/python3/dist-packages/kvirt/cli.py", line 1536, in create_vm
    result = config.create_vm(name, profile, overrides=overrides, customprofile=customprofile,
  File "/usr/lib/python3/dist-packages/kvirt/config.py", line 953, in create_vm
    result = k.create(name=name, virttype=virttype, plan=plan, profile=profilename, flavor=flavor,
  File "/usr/lib/python3/dist-packages/kvirt/providers/kvm/__init__.py", line 863, in create
    self._uploadimage(name, pool=default_storagepool, origin=tmpdir)
  File "/usr/lib/python3/dist-packages/kvirt/providers/kvm/__init__.py", line 2521, in _uploadimage
    with open(f"{origin}/{name}", 'rb') as ori:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_p3oh_3c/test-1.ISO'
```

It seems as though there should be a volume at this /tmp location and there is not, or that it should be looking for the one that was created in  `/var/lib/libvirt/images`?

I last used kcli on Ubuntu several months ago, so I am not sure if I am missing a new configuration step (I couldn't find anything in the docs similar) or if it is a bug.

**Comment by karmab** [comment]
The command that's being used to generate this iso is silently failing, which is uncommon.
I've added a commit https://github.com/karmab/kcli/commit/276481f39591b74b66bb5f889a9d096a248d190b so that at least the error gets captured

**Comment by cmaf** [comment]
Thank you! This is resolved, I was missing the `xorriso` package.
