### ISSUE TITLE
illegal base64 data at input byte 0

### ISSUE THREAD

**Issue by jhelbling** [karmab/kcli#641]
Bootstrap node is in loop try. OCP running without any issues with pull secrets from RHEL

parameter.yaml

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'

kcli version
version: 99.0 commit: 7a13d9e 2024/02/18 Available Updates: True

bootkube.sh[13132]:         * illegal base64 data at input byte 0
bootkube.service: Main process exited, code=exited, status=1/FAILURE

**Comment by karmab** [comment]
fixed by https://github.com/karmab/kcli/commit/49efdb9d2c3e1e5ad696aea89cfd46fdb8b717ed
