### ISSUE TITLE
To ensure each cluster operator has finished progressing hang

### ISSUE THREAD

**Issue by jhelbling** [karmab/kcli#643]
![Uploading Screenshot 2024-02-21 at 16.42.24.png…]()
version: 99.0 commit: 6461283 2024/02/21 Available Updates: False

Version
4.15.0-0.okd-2024-02-10-035534
Status
 Progressing
Message
SyncLoopRefreshProgressing: Working toward version 4.15.0-0.okd-2024-02-10-035534, 1 replicas available

DegradedFalse

21 Feb 2024 at 16:18
AsExpectedAll is well

All operators are up, but console is hangs.

INFO Waiting up to 30m0s (until 4:53PM CET) to ensure each cluster operator has finished progressing...

Message: Please delete the plan will be show after 30m

**Comment by karmab** [comment]
hello! can you share the parameter file you're using (since the nightly okd ci works fine) ?

**Comment by karmab** [comment]
as the nightly job works fine, I m closing it for now, but feel free to reach out on slack so we troubleshoot live

ps: make sure to assign enough resources to your nodes for the install to succeed, as a reference, you can check the paramfile I use for nightly run here https://github.com/karmab/kcli/blob/main/openshift-ci-paramfiles/okd.yml

**Comment by jhelbling** [comment]
version: stable
network_type: OVNKubernetes
ovn_hostrouting: true
tag: '4.15'
ctlplanes: 1
ctlplane_memory: 16384
ctlplane_numcpus: 24
workers: 5
memory: 131072
disk_size: 80
nameserver: 192.168.122.253
worker_memory: 32768
worker_numcpus: 16
bootstrap_memory: 16384
pullSecret: fake_pull.json
extra_disks:
