### ISSUE TITLE
Make KCLI support controlling the Spot VM `On VM termination` policy

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#652]
The default is to "just" `Stop` the `VM`. However, in certain use-cases. E.g. when using `spot vm instances` it might certainly be a better idea to set this policy to `delete`. The thinking being that if the VM was preempted and this is a `Kubernetes cluster` then the VM is likely of no use later on over the lifetime of the cluster.

So this is a feature request to get `KCLI` to support `KCLI Spot Instances` while at the same time supporting configuring the `Spot VM instances.

Thank you @karmab

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/cd4f874102ce3711c0de14d9166bf9dd85b837f9 via spot_delete parameter
