### ISSUE TITLE
Please upload source distributions to pypi

### ISSUE THREAD

**Issue by oz123** [karmab/kcli#655]
Hi! 

Can you please also upload source distributions to pypi in addition to built wheels?

**Comment by karmab** [comment]
Hello! can you explain the benefit?

**Comment by oz123** [comment]
This allows upstream distributions to package the code in their own ways, for example. Alternatively, you can publish tags on GitHub.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/63a2a2306a336679f234e2bd6d4a3cf71186666f
