### ISSUE TITLE
NIC for keepalived should be calculated on every run of the init container

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#656]
As per current source code, replacements on `/etc/kubernetes/keepalived.conf` happen only once, the first time they are needed. This means that the NIC is set once (during cluster first startup) and then is fixed.

This is not correct as long as the NIC name may change during the cluster lifetime. The easiest use case is testing a migration between OpenShiftSDN and OVNKubernetes network plugins, during which we change from the default interface name (`ens3` in my libvirt environment) to the OVN bridge `br-ex`.

Other possible use cases would be unexpected NIC name changes during reboots (I have never seen this happening in libvirt, but I would not discard this to happen in other environments, like vmware).

Best implementation suggestion: do something more similar to what on-prem OCP does today, which is to keep a separated "template file" always around and render it unconditionally in the init container in the definitive keepalived.conf file (even if "rendering" here means some simpler invocations of `sed`, because we don't need something more sophisticated).

**Comment by palonsoro** [comment]
Currently, during a migration between OpenShiftSDN and OVNKubernetes, we need to manually edit the keepalived.conf to fix the IP. Until we fix, the control plane VIP is unavailable due to wrong keepalived configuration.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/c2ec1457ce1c56a95ea489b976eeae58a425f554
