### ISSUE TITLE
Clone with -f fails

### ISSUE THREAD

**Issue by kevinclevenger** [karmab/kcli#658]
AlmaLinux 9.3
Python 3.9.18

\# kcli clone -b arch -f a2
Cloning vm a2 from vm arch...
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 5512, in cli
    args.func(args)
  File "/usr/lib/python3.9/site-packages/kvirt/cli.py", line 1666, in clone_vm
    result = k.clone(base, name, full=full, start=start)
  File "/usr/lib/python3.9/site-packages/kvirt/providers/kvm/__init__.py", line 2283, in clone
    oldpath = source.get('file')
AttributeError: 'NoneType' object has no attribute 'get'

\# kcli clone -b arch a2  completes without issues

**Comment by karmab** [comment]
can you share output of `kcli --debug info vm arch` ?

**Comment by kevinclevenger** [comment]
[arch.debug.txt](https://github.com/karmab/kcli/files/14891898/arch.debug.txt)

**Comment by karmab** [comment]
This is actually fixed by https://github.com/karmab/kcli/commit/32f001908d290b5d6a63b3a687eca9d0aa8784c0
The issue was due to the fact that your cdrom didnt have any source file (which is perfectly valid)

**Comment by kevinclevenger** [comment]
Great, thank you! BTW, really liking kcli.
