### ISSUE TITLE
kcli tries to create a VM with an IP in use by a powered off VM

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#662]
Steps to reproduce:
- Have `reserveip: true`,  `reservedns:true` and `reservehost: true` in `~/.kcli/config.yml`
- Have some created VMs powered off.
- Try to create a new VM.
- None of the VMs were given an explicit IP on creation time.

If you are unlucky enough, it picks one of the IPs used by the powered off VMs and fails while trying to add the DNS record (the VM is still created with the wrong IP.

Not sure if this may be expected behavior that IP reservation only happens if the IP is given explicitly. If it is, it should be explicitly documented as such. However, IMHO, one would expect that if you ask an IP to be reserved, it is always reserved, not only when it was chosen automatically.

Thanks in advance.

**Comment by karmab** [comment]
reserveip only makes sense along with a specific ip, I ll make it clear in the doc and via a warning in the code if not specified

**Comment by palonsoro** [comment]
Ok

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/fbf766ca3f7e929131ba646bef501a0122e87e26
