### ISSUE TITLE
Microshift not deploying

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#664]
Not sure if this is my mistake or a bug, tbh. But if I try to deploy this microshift, I get an exotic error:
```
$ cat parameters-yoda.yml
KUBECONFIG: /var/lib/microshift/resources/kubeadmin/kubeconfig
cluster: yoda
disk_size: 30
domain: ocp.example.com
extra_disks: [60]
image: rhel9
kubeconfig_acm: None
memory: 2048
network: ocp
nodes: 1
noname: False
numcpus: 2
olm: False
podman: False
pull_secret: openshift_pull.json
register_acm: False
rhnorg: REDACTED
rhnactivationkey: REDACTED
sslip: True
tag: 4.15
version: stable

$ kcli create kube microshift --paramfile /root/microshift-clusters/parameters-yoda.yml yoda                                                                                                                                                                                                 
Deploying Vms...
yoda-0 not deployed because Origin file /usr/lib/python3.9/site-packages/kvirt/cluster/microshift/None not found for yoda-0
The following vms failed: yoda-0
```

Is this a bug or where may I have made a mistake? Thanks in advance.

**Comment by karmab** [comment]
Is this happening with latest?

**Comment by palonsoro** [comment]
Latest version available in RPM on CentOS Stream 9

**Comment by palonsoro** [comment]
Wait, it was latest yesterday. Let me check with today's...

**Comment by karmab** [comment]
the issue is that you specified `kubeconfig_acm: None` which means that kubeconfig_acm is evaluated to the string None instead of None/null object (which you would get with `kubeconfig_acm: `)

**Comment by karmab** [comment]
although a correct solution is to remove the line kubeconfig_acm from your parameter file (or to make sure it evaluates to a None object), I 've added a fix to only inject kubeconfig_acm when it points to a valid/existing path
https://github.com/karmab/kcli/commit/fef9f90d450be45d36c4b01cd27fd02d36e31539

**Comment by palonsoro** [comment]
Ok. Thanks. I knew it was likely due to some typo (this is what happens when you copy-paste `kcli info cluster microshift` output. Thanks!
