### ISSUE TITLE
microshift does not allow passing rhnorg/rhnactivationkey parameters

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#665]
If I try to deploy micronshift with kcli and I provide `rhnorg` and `rhnactivationkey` as parameters, they are not forwarded to the VM, so it complains that they are absent and the VM is not registered.

Maybe it has to do with the fact that the internal plan does not seem to forward them.

**Comment by karmab** [comment]
fixed here https://github.com/karmab/kcli/commit/f64eb669d3ca982b4eaf5cd6de25ca540dd7938b

**Comment by palonsoro** [comment]
Thx!
