### ISSUE TITLE
Is hierarchical path for datastore (pool) supported for vSphere?"

### ISSUE THREAD

**Issue by nis-ste** [karmab/kcli#666]
For example, my datastore path on vSphere looks like this:

`EXAMPLE_DC/Level1/Level2/Level3/dc1_openshift_datastore_1_ssd`

which I define as a pool in the `~/.kcli/config.yml`:
```yaml
mysphere:
 ...
 ...
 pool: "EXAMPLE_DC/Level1/Level2/Level3/dc1_openshift_datastore_1_ssd"
```

If I list all host infos with the command:

```
kcli info host
```

all datastores are listed just by their names, without their hierarchical path.

if i try to use the hierarchical path to the datastore like metioned above, i get a `KeyError` exception from 

[https://github.com/karmab/kcli/blob/fbf766ca3f7e929131ba646bef501a0122e87e26/kvirt/providers/vsphere/__init__.py#L188](https://github.com/karmab/kcli/blob/fbf766ca3f7e929131ba646bef501a0122e87e26/kvirt/providers/vsphere/__init__.py#L188)

(Line 188): `if datastores[pool] != self.dc.name:`

If I get it right, arround line 1626 the datastore names are just added by their plain name not by a full path or uuid.

**Comment by karmab** [comment]
what does kcli list pool print in your case?

**Comment by karmab** [comment]
closing as I m not able to create a nested hierarchical datastore to explore how it should behave
