### ISSUE TITLE
Disconnected docs may be outdated

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#668]
I see that the documentation in https://kcli.readthedocs.io/en/latest/ reference `disconnected_deploy` parameter. However, while grepping in the source  code, I only see references to it in some examples and docs, not in any relevant source code.

Is this documentation up-to-date? Maybe it should point to `disconnected_vm`?

Thanks and regards.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/c85136d2b4e04b950142497365fab370c72b8f6d

**Comment by palonsoro** [comment]
Thx
