### ISSUE TITLE
baremetal_iso_ctlplane howto

### ISSUE THREAD

**Issue by lfarkas** [karmab/kcli#673]
in the docs:
https://kcli.readthedocs.io/en/latest/#baremetal-hosts-support
you state 
"You can also create isos only for a given role using the boolean baremetal_iso_bootstrap, baremetal_iso_ctlplane and baremetal_iso_worker"
but how can i create and iso for install a control place? i don't see any example only "through this workflow", but what does it means?
it'd be useful to show an example for such an iso generation.

**Comment by karmab** [comment]
i ll update the doc to make it clear but what it means is that you can use kcli create cluster openshift with baremetal workers, in which case an iso is generated that can be plugged via redfish.
the list of baremetal nodes is specified as part of the yaml parameter file where one typically provides data such as target version,tag,domain, workers number,erc

**Comment by gcsontos** [comment]
Can I use kcli to generate all of the iso-s (bootstrap/controlplane/worker) and boot them via USB? I mean every component will be a sepearte baremetal server.
I've used the "kcli create openshift-iso" command to generate an iso, but it is just for worker node.

**Comment by karmab** [comment]
sorry for the delay, 
if you want to do a baremetal only install of openshift using kcli, you can use a command such as the following one

```
kcli create cluster openshift -P sno=true -P sno_ctlplanes=true -P sno_workers=true xxx -P api_ip=192.168.122.245
```

This would generate three isos (in your default libvirt pool):
- xxx-sno.iso to plug to your first ctlplane
- xxx-ctlplane.iso to plug to your other ctlplanes
- xxx-worker.iso to plug to your workers

This workflow is a special case of sno (and as such leverages bootstrap in place, so no bootstrap node is needed) but you do need to specify an api ip if you have several ctlplanes

By  default, the install will wait for you to plug the corresponding isos, but you can also define your hosts with the baremetal_hosts to have them boot with the iso using redfish. This assumes you have an apache server running where you launch the deployment

If you only want the isos and dont wait for install to actually succeed, pass false to the flag sno_wait
