### ISSUE TITLE
Traceback with proxmox list vms

### ISSUE THREAD

**Issue by kevinclevenger** [karmab/kcli#674]
kcli current git
python-proxmoxer 2.0.1-5

103 is a container ...

$ kcli -c proxmox list vms
Proxmox provider is Work In Progress. Use at your own risk!
Traceback (most recent call last):
  File "/home/anon/.local/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anon/.local/lib/python3.12/site-packages/kcli-99.0-py3.12.egg/kvirt/cli.py", line 5512, in cli
    args.func(args)
  File "/home/anon/.local/lib/python3.12/site-packages/kcli-99.0-py3.12.egg/kvirt/cli.py", line 749, in list_vm
    _list = config.k.list()
            ^^^^^^^^^^^^^^^
  File "/home/anon/.local/lib/python3.12/site-packages/kcli-99.0-py3.12.egg/kvirt/providers/proxmox/__init__.py", line 142, in list
    vm_config = self.conn.nodes(vm["node"]).qemu(vm["vmid"]).config.get()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/proxmoxer/core.py", line 169, in get
    return self(args)._request("GET", params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/proxmoxer/core.py", line 149, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 500 Internal Server Error: Configuration file 'nodes/proxmox/qemu-server/103.conf' does not exist

Other commands work ...

$ kcli -c proxmox list disks
Proxmox provider is Work In Progress. Use at your own risk!
Listing disks...
+---------------------+-------------------+--------------------------------+
| Name                |        Pool       |              Path              |
+---------------------+-------------------+--------------------------------+
| base-100-disk-0     | proxmox/local-lvm |   local-lvm:base-100-disk-0    |
| base-106-disk-0     | proxmox/local-lvm |   local-lvm:base-106-disk-0    |
| base-107-disk-0     | proxmox/local-lvm |   local-lvm:base-107-disk-0    |
| base-108-disk-0     | proxmox/local-lvm |   local-lvm:base-108-disk-0    |
| base-109-disk-0     | proxmox/local-lvm |   local-lvm:base-109-disk-0    |
| vm-101-disk-0.qcow2 |   proxmox/export  | export:101/vm-101-disk-0.qcow2 |
| vm-110-disk-0       | proxmox/local-lvm |    local-lvm:vm-110-disk-0     |
+---------------------+-------------------+--------------------------------+

$ kcli -c colibri list pools
Proxmox provider is Work In Progress. Use at your own risk!
+-------------------+------------------+
| Pool              |       Path       |
+-------------------+------------------+
| colibri/export    |     /export      |
| colibri/local-lvm | [lvmthin] vg:pve |
+-------------------+------------------+

**Comment by karmab** [comment]
ugly fix here https://github.com/karmab/kcli/commit/26ecaad8f39d2a9413ec02e2dc9fc96dbacf81d2
