### ISSUE TITLE
RFE: Please use $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by kevinclevenger** [karmab/kcli#675]
Please use $XDG_CONFIG_HOME/.kcli instead of $HOME/.kcli

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by karmab** [comment]
that might make sense but I need to evaluate whether it's not a too disruptive change (for instance if this value is likely not to be set to some random value on most boxes, which would break people's current setup)

**Comment by kevinclevenger** [comment]
If $XDG_CONFIG_HOME isn't set perhaps 
1. check if ~/.config/kcli already exists and if so use that
2. if not check if ~/.kcli already exists and if so use that
3. if neither exist create ~/.config/kcli by default

The point is that applications shouldn't be using ~/ directly for anything for some years (either ~/.cache, ~/.config, or the ~/.local hierarchy depending on what's being stored)

**Comment by karmab** [comment]
well, my issue is that falling back to ~/.kcli which I intend to keep isnt compliant with the specification.
Also having different locations is confusing for the end user.
So while I think the request would have made sense originally, at this moment of the project, it would cause issues

**Comment by karmab** [comment]
while I have considered the request,I feel it's a too disruptive change to apply at this stage of the project :(
