### ISSUE TITLE
error rendering inputfile /usr/lib/python3.9/site-packages/kvirt/cluster/openshift/disconnected/scripts/mirror-config.yaml.sample. Got: 'disconnected_operators' is undefined

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#676]
When I try to update the openshift-registry from a paramfile that doesn't specify `disconnected_operators`, I get the following error:
```
error rendering inputfile /usr/lib/python3.9/site-packages/kvirt/cluster/openshift/disconnected/scripts/mirror-config.yaml.sample. Got: 'disconnected_operators' is undefined
```

Same happens also for `disconnected_certified_operators`, `disconnected_community_operators`, `disconnected_marketplace_operators` and `disconnected_extra_catalogs`.

As a workaround, I can set them all to empty arrays like below:
```
kcli update openshift-registry --paramfile /root/OCP4-clusters/parameters-revali-ovn-4.15.yml -P tag=4.15.11 -P disconnected_operators=[] -P disconnected_certified_operators=[] -P disconnected_community_operators=[] -P disconnected_marketplace_operators=[] -P disconnected_extra_catalogs=[]
```

However, a more proper handling of the absent values would be preferable.

**Comment by karmab** [comment]
addressed here https://github.com/karmab/kcli/commit/7909e116fd84662ad72ee2b22133ee54a4f15f8e

**Comment by palonsoro** [comment]
Thanks!
