### ISSUE TITLE
kcli waits for IP assignment when `start=false`, `reservedns=true` and there is no static IP

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#686]
If one creates a VM in the following scenario:
- `start=false` (VM not powered on after creation, e.g. because it is empty)
- `reservedns=true` (usual default)
- No IP is statically defined in `nets` parameter

Then kcli waits forever for an IP to be assigned, although that won't happen because the VM is not powered on.

This should be improved somehow, by taking either of these approaches:
- In the scenario above, emit a warning that DNS cannot be reserved without static IP or starting the VM and behave as if `reservedns=false` (user should be able to use `kcli create dns` to create the DNS entry later, right?)
- Error out in the scenario above, asking the user to either set `reservedns=false`, `start=true` or a static IP in the first NIC.
- Compute a random static IP for the first NIC and automatically use it as if the user had specify it (worth emitting a warning if this approach is taken).

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/c57364c22c058a412304c14bc8e57a9f0a2a6729
(note that reservedns defaults to false)

**Comment by palonsoro** [comment]
Thanks
