### ISSUE TITLE
Cannot create dns entries for a VM with the same name than the VM in a plan

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#696]
Use case:
- Plan consisting of empty non-started machines (on libvirt).
- I reserve their IPs.
- I want to create DNS names for those reserved IPs (which is not possible because `reservedns` is now ignored, because it can cause issues if the IP is not reserved).

Problem:
- In plans, the key (in the root dictionary of the plan yaml) is the name of the item, regardless of the type.
- Keys in a YAML dictionary have to be unique.
- DNS names force the host to be equal to the name of the DNS item you are creating.
- If I try to create a `dns` for `myvm` vm in the same plan than `myvm` vm, I cannot because the VM definition has `myvm` as key, so if I add the dns also with `myvm` key, I am adding two items with the same key to the yaml.

Possible solutions:
- Implement some kind of generic item name override for plans. That way, resources of different kinds but with the same name can be created by a plan.
- Add an `only_aliases` option so that it only associates the IP to the aliases provided and not to the name of the DNS item created.

**Comment by karmab** [comment]
I think I actually fixed it in https://github.com/karmab/kcli/commit/663f26dea122e15e0aee42ca86a7fcdb2a384fd4 when realizing today that it was legit to reserve a dns entry for a non started vm as long as an ip was provided

**Comment by karmab** [comment]
regarding the way a plan is handled, I dont have a good solution for that, it's just the way yaml is parsed and I think any "hack" would make the plan more complex to understand

**Comment by palonsoro** [comment]
Why not just adding an `alt_name` field that overrides the name of the created item?

**Comment by karmab** [comment]
it's not possible because the behaviour or pyyaml with duplicate keys is to override the corresponding entry with the last key.
furthermore, yaml spec indicates that keys shouldnt be duplicated in a yaml file so I m thinking that instead I should throw an error with duplicates

**Comment by palonsoro** [comment]
I don't mean that. 

For example, let's have a look at this snippet:

```yaml
myvm-vm:
  alt_name: myvm # This parameter causes the VM to have "myvm" name and the key is ignored
  cpus: 2
  memory: 8192
  ...

myvm-dns:
  type: dns
  alt_name: myvm # This parameter causes the VM to have "myvm" name and the key is ignored
  ip: 192.168.192.34
````

The idea is to introduce an `alt_name` parameter that defines the name of the item to be created and makes the key to be ignored, such that in the snippet above, both the VM and the DNS entry have `myvm` name and the `myvm-vm` and `myvm-dns` keys are ignored (they just need to be different to avoid the collision, but they can be anything because name is defined in `alt_name` and not in the key).

To ensure backwards compatibility, `alt_name` should be optional and fail back to the key if absent (i.e. to the current behavior)

**Comment by karmab** [comment]
I need to do a bit of testing but I believe https://github.com/karmab/kcli/pull/698 should address this.
It will:
- parse the plan yaml so that items of the same type are grouped together, allowing the same name to be reused if the type is different
- throw an error if the same name is used twice with the same type

**Comment by palonsoro** [comment]
Ok, so basically when #698 is merged, having more than one key equal of different type would be acceptable, right? I just hope it is not problematic with the YAML parser...

**Comment by karmab** [comment]
it's merged already and works as expected

**Comment by palonsoro** [comment]
Confirmed that it works now as expected even when using jinja templating. Thanks!
