### ISSUE TITLE
kcli create sushy-service should create services under /usr/local/lib/systemd/system or /etc/systemd/system

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#697]
As per `man systemd.unit`, the `/usr/lib/systemd/system` path is for "System units installed by the distribution package manager", so it is not appropriate for units generated by a command like `kcli create sushy-service`.

In that regard, either of these options would be more appropriate:
- `/usr/local/lib/systemd/system`: "System units installed by the administrator"
- `/etc/systemd/system`: "System units created by the administrator"

The former looks better than the latter IMHO, as it better allows ad-hoc overrides on top of a base unit you wouldn't touch that often.

But anyway, it is important to try to use the paths properly, because as far as I have seen, correct adherence to file system path guidelines is usually very expected (and found) in systemd world.

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/a028fefaa800c3d34f9f2dcf37278ab3656b5cb9
