### ISSUE TITLE
Hugepages and Multiple Page size support for the kcli VMs

### ISSUE THREAD

**Issue by ElCoyote27** [karmab/kcli#703]
Hi,

Although the hypervisor kernel defaults to 2Mb hugepages it can handle both 2Mb and 1Gb hugepages on the same machine.

Here a RHEL8 system with 2Mb hugepages and zero 1Gb hugepages:
```
# ls -l /sys/kernel/mm/hugepages/hugepages-*/nr_hugepages
-rw-r--r--. 1 root root 4096 Jul 10 07:57 /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
-rw-r--r--. 1 root root 4096 Jul 10 07:57 /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

# cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
0
# cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
417792
```

for a KVM VM on the default 2Mb pages, the VM's XML will have this:
```
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
```

for a KVM VM on the 1Gb pages, the VM's XML will have this:
```
<memoryBacking>
  <hugepages>
    <page size='1048576' unit='KiB'/>
  </hugepages>
</memoryBacking>
```

on systems with over 128GB RAM, using only 4k pages results in huge TLBs and reduces performance.
in both cases, VM memory needs to be a multiple of the VM memory size.

IMVHO the monolithitc 'hugepages' kcli var should be split in '2mb_hugepages' and '1gb_hugepages'.

My 2c,

**Comment by karmab** [comment]
thanks for the clarification!
addressed in https://github.com/karmab/kcli/commit/54ea98071d756ffb0585acafbc586eb90a1972ba
