### ISSUE TITLE
kcli seems not to support the deployment of a single control-plane K3s cluster.

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#704]
The error:

```text
Deploying Vms...
minio-prod-ctlplane-0 not deployed because Error rendering script file /home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/site-packages/kvirt/cluster/k3s/bootstrap.sh. Got: 'first_ip' is undefined
The following vms failed: minio-prod-ctlplane-0
```

This, according to my analysis, seem to happen because:

- the code at [LOC207 in k3s init.py](https://github.com/karmab/kcli/blob/main/kvirt/cluster/k3s/__init__.py#L207)
- tries to fetch the value to be used for the `first_ip` variable by looking up the IP of ctlplane-0 via the `first_info.get` method

However, this cannot succeed .. as seen if one moves the following lines above this line [LOC204 in k3s init.py](https://github.com/karmab/kcli/blob/main/kvirt/cluster/k3s/__init__.py#L204)

```python
    first_info = config.k.info(f'{cluster}-ctlplane-0')
    first_ip = first_info.get('private_ip') or first_info.get('ip')
    data['first_ip'] = first_ip
```

which results in: `VM CLUSTER_NAME-ctlplane-0 not found`.

---

## Suggestion

In the case that a single `control-plane node K3s cluster` is tried deployed I suggest that `KCLI` gets the `IP` to be used as the value to `first_ip` in another way ( obviously ). The issue is that there's several use-cases to cover here.

1. end-users of `KCLI` using `vmrules` and
2. users that does not

In the case that `vmrules` are used then the `ip value for first_ip` can be fetched from: `vmrules >> cltplane-0 >> nets >> ip` from the cluster KCLI parameter file. In the use-case where `vmrules` is **NOT** used it's harder.

Hmm.

1. prompt the user?
2. DHCP?

I'm steadily of the opinion that `control-plane nodes in Kubernetes clusters` should have static IP's and the same one full the life-time of the nodes.

**Comment by karmab** [comment]
fixed in https://github.com/karmab/kcli/commit/ff1d2fda24258261d8872b57e3ccee7ab590a331

**Comment by larssb** [comment]
Aaaah see my comments in #705
