### ISSUE TITLE
ODF: make ceph-tools configurable?

### ISSUE THREAD

**Issue by ElCoyote27** [karmab/kcli#706]
Just a simple query but it's often useful to have ceph-tools with ODF.
They can be enabled this way:

# ODF 4.14 and below:
if [[ ${KVV} -le 14 ]]; then
        oc patch OCSInitialization ocsinit -n openshift-storage --type json --patch  '[{ "op": "replace", "path": "/spec/enableCephTools", "value": true }]'
fi

# ODF 4.15 and above:
if [[ ${KVV} -ge 15 ]]; then
        oc patch storagecluster odf-storagecluster -n openshift-storage --type json --patch '[{ "op": "replace", "path": "/spec/enableCephTools", "value": true }]'
fi

**Comment by karmab** [comment]
added in https://github.com/karmab/kcli/commit/ec8c845e04ce6266b1cf7cbbd98bd5b60502015f via odf_cephtools boolean
