### ISSUE TITLE
kcli v20240811 defaults to 1Gb hugepages even on a machine with only 2Mb hugepages

### ISSUE THREAD

**Issue by ElCoyote27** [karmab/kcli#707]
I have 'hugepages: true' in my param file.
Here's my system setting:
```
# cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
417792
# cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
0
```
that's about 800Gb RAM in 2Mb hugepages and no 1Gb hugepages.

When I used the latest kcli to launch a cluster, here's what happens:
```
# rpm -q kcli
kcli-99.0.0.git.202408050819.515de6e-0.el8.x86_64


# virsh start ocp4d-bootstrap
error: Failed to start domain 'ocp4d-bootstrap'
error: internal error: process exited while connecting to monitor: 2024-08-13T13:12:38.598261Z qemu-kvm: Memory backend 'pc.ram' not found

# virsh dumpxml ocp4d-bootstrap|grep -iC2 huge
  <currentMemory unit='KiB'>16777216</currentMemory>
  <memoryBacking>
    <hugepages>
      <page size='1024' unit='KiB'/>
    </hugepages>
    <locked/>
  </memoryBacking>
```

Even though I did not define 'hugepages_1gb', kcli is still trying to use them.
A user could have both 2Mb and 1Gb hugepages on the same system. and I might want to launch the Masters on 2Mb hugepages while my workers are consuming 1Gb hugepages.

**Comment by karmab** [comment]
as per the code, I think it only happens if hugepages_1gb is set

**Comment by ElCoyote27** [comment]
yes, but I did not have it set anywhere.
The 'locked' parameter seems wrong, though..

**Comment by ElCoyote27** [comment]
I agree that the above code (your code) should have been fine but that fact is that on my machine (which has only 2mb pages and only hugepages: true) the update from 0805 to 0811 made the kcli try to create a VM backed by 1G pages.
If I apply the patch in the PR, things work again as expected.
Happy to tmate with you again if you'd like to.

**Comment by karmab** [comment]
closing since fix made its way in the code
