### ISSUE TITLE
Release notes 10.0 link is broken...

### ISSUE THREAD

**Issue by jtudelag** [karmab/kcli#71]
...
https://github.com/karmab/kcli/blob/master/changelog/10.1.md

**Comment by karmab** [comment]
actually no, the changelogs was moved to a github wiki
so  https://github.com/karmab/kcli/wiki contains release notes per version

**Comment by jtudelag** [comment]
Well, this is the link you get when you are subscribed to the repo, and notified by mail....
https://github.com/karmab/kcli/blob/master/changelog/10.1.md

**Comment by karmab** [comment]
ok, guthub weirdness then, i ve fixed it somehow
