### ISSUE TITLE
`reservedns` should be forced to false on a network that was created with `dns=no`

### ISSUE THREAD

**Issue by palonsoro** [karmab/kcli#725]
Steps:
- Have a global configuration where `reservedns: true`
- Try to create a VM in a network that was created in a network with `dns=false` and `dhcp=false` (because you have your own dhcp server around).

Expected result: Not to try `reservedns`

Actual result: `reservedns` logic is tried during VM creation and it behaves buggy (it waits forever to grab an IP, even when such an IP was grabbed from the custom DHCP server and VM creation becomes stuck).

**Comment by karmab** [comment]
fair enough, addressed in https://github.com/karmab/kcli/commit/9ba09a6a141423c325f6698797f729a003da9183

**Comment by palonsoro** [comment]
Thanks!
