### ISSUE TITLE
How to uniformly change the names of network cards

### ISSUE THREAD

**Issue by BurlyLuo** [karmab/kcli#735]
For virt-intall tool. we always set the nic with eth0 eth1 eth2... 
but with kcli, centos series which begin from eth0. but ubuntu/debian which are begin from ens3 ens4
so , can we unify the nic name with at nets OPT
which like:
```"[{'name':'brnet','ip':'192.168.2.96','netmask':'24','gateway':'192.168.2.1','interface_name': 'eth0'},{'name':'vppdpdk5'},{'name':'vppdpdk8','interface_name': 'eth1'},{'name':'vppdpdk9'}]"```

**Comment by karmab** [comment]
I dont think virt-install has any trick to force the nic name, it's a guest OS thing

**Comment by BurlyLuo** [comment]
Oh, yes, but we still can self-define the interface name . it should be a pretty option. hope we can support this. thanks.

**Comment by karmab** [comment]
I think it's not possible, with kcli or with some other tool

**Comment by karmab** [comment]
here's a workaround for you, which will work on kvm only
add the following parameter to your vm creation call -P cmdline="net.ifnames=0"

**Comment by BurlyLuo** [comment]
There is a new way:
```
# [root@rowan> images]# cp -r openEuler2403 openEuler2403.bak
[root@rowan> images]# virt-customize -a /var/lib/libvirt/images/openEuler2403 --edit '/etc/default/grub:s/GRUB_CMDLINE_LINUX=".*"/GRUB_CMDLINE_LINUX="console=tty1 console=ttyS0 rootfstype=ext4 quiet oops=panic softlockup_panic=1 nmi_watchdog=1 rd.shell=0 selinux=0 crashkernel=256M panic=3 net.ifnames=0"/g'
[   0.0] Examining the guest ...
[   3.7] Setting a random seed
[   3.8] Editing: /etc/default/grub
[   3.9] Finishing off
[root@rowan> images]# 
[root@rowan> images]# virt-cat -a /var/lib/libvirt/images/openEuler2403 /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="console=tty1 console=ttyS0 rootfstype=ext4 quiet oops=panic softlockup_panic=1 nmi_watchdog=1 rd.shell=0 selinux=0 crashkernel=256M panic=3 net.ifnames=0"
GRUB_DISABLE_RECOVERY="true"
GRUB_DISABLE_OS_PROBER="true"
[root@rowan> images]# virt-customize -a /var/lib/libvirt/images/openEuler2403 --run-command 'grub2-mkconfig -o /boot/grub2/grub.cfg'
[   0.0] Examining the guest ...
[   3.5] Setting a random seed
[   3.6] Running: grub2-mkconfig -o /boot/grub2/grub.cfg
[   4.0] Finishing off
[root@rowan> images]# virt-cat -a /var/lib/libvirt/images/openEuler2403 /boot/grub2/grub.cfg | grep 'net.ifnames=0'
        linux   /vmlinuz-6.6.0-28.0.0.34.oe2403.x86_64 root=UUID=1f4c3ba2-226d-4365-8d1f-30d80117c355 console=tty1 console=ttyS0 rootfstype=ext4 quiet oops=panic softlockup_panic=1 nmi_watchdog=1 rd.shell=0 selinux=0 crashkernel=256M panic=3 net.ifnames=0 
[root@rowan> images]# 
```

with ```-P cmdline="net.ifnames=0"```. seems doesn't work.

**Comment by karmab** [comment]
for this flag to work, you'll need to have virt-customize binary available, (which comes as part of guestfs-tools rpm)

**Comment by BurlyLuo** [comment]
Yes. it should be. 
but with ```-P cmdline="net.ifnames=0"```.  seems doesn't work. when i test with openeuler2403.

**Comment by BurlyLuo** [comment]
Oh, Okay. there is no such kind of OS. (which like OpenEuler which like a ubuntu+centos) 
if you have a intrest to add the such type into the dict. it will be fine. 
or will use virt-customize  tool.
