### ISSUE TITLE
kcli doesn't have the bootstrap option anymore? 

### ISSUE THREAD

**Issue by kundeng** [karmab/kcli#737]
How do I use a local KCLI config file that defaults to the local directory or through an environment variable such as KCLI_CONFIG?

There used to be a "kcli bootstrap" command that generated one, but it seems that the command is no longer available.

**Comment by karmab** [comment]
I vaguely recall such a subcommand, long time ago :)
anyway, you can use `kcli create host` subcommands to achieve the same effect

**Comment by kundeng** [comment]
what I mean is whether I can use environment variable to put to the config file for use?  I would like to package the config file along with other files.

**Comment by karmab** [comment]
you can indeed use the environment variable KCLI_CONFIG to point to a config file of yours
