### ISSUE TITLE
KCLI does not always complete the deployment of a K3s VM on GCP.

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#739]
Here's the scenario.

- Our auto-scaling solution was automatically triggered to scale in a worker on X K3s cluster

Looking at the logs of the `auto-scaling Pod` I see:

```text
2024-11-04 20:02:12.102	Waiting for disk test-test-worker-124-disk1 to be ready
2024-11-04 20:02:12.102	Waiting for disk test-test-worker-124-disk2 to be ready
2024-11-04 20:02:12.102	Waiting for disk test-test-worker-124-disk3 to be ready
2024-11-04 20:02:12.102	Waiting for disk test-test-worker-124-disk4 to be ready
2024-11-04 20:02:12.102	Waiting for disk test-test-worker-124-disk5 to be ready
2024-11-04 20:02:12.102	Waiting for disk test-test-worker-124-disk6 to be ready
2024-11-04 20:02:12.102	Waiting for disk test-test-worker-124-disk7 to be ready
2024-11-04 20:02:12.102	Waiting for disk test-test-worker-124-disk8 to be ready
2024-11-04 20:02:12.102	test-test-worker-124 deployed on gcp-test
```

Successful runs will have:

```text
Waiting for disk test-test-worker-119-disk1 to be ready
Waiting for disk test-test-worker-119-disk2 to be ready
Waiting for disk test-test-worker-119-disk3 to be ready
Waiting for disk test-test-worker-119-disk4 to be ready
Waiting for disk test-test-worker-119-disk5 to be ready
Waiting for disk test-test-worker-119-disk6 to be ready
Waiting for disk test-test-worker-119-disk7 to be ready
Waiting for disk test-test-worker-119-disk8 to be ready
test-test-worker-119 deployed on gcp-test
Workers Nodes will join the cluster in the following minutes
Updating ip alias ranges
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
Waiting 5s for 9 nodes to have a Pod CIDR assigned
```

Looking at the code of `KCLI`:

- Having `threaded: true` in the clusters `KCLI parameter file`
- "We" get past the call to `handle_response` in [common/__init__.py](https://github.com/karmab/kcli/blob/main/kvirt/common/__init__.py#L662)
- Then `handle_vm_result()` is called
- I therefore think that somewhere between LOC3270-3294 in [handle_vm_result in kvirt/config.py](https://github.com/karmab/kcli/blob/main/kvirt/config.py#L3270-L3294) something is erring. But, without throwing an error.

I'm certainly **NOT** 100% that the above holds ... you're the expert here @karmab ... However, the introduced node never gets fully bootstrapped. You know:

- Pod CIDR range on the node
- worker label and other meta-data

And therefore never becomes a fully working member of the cluster.

For debugging purposes here's a sanitized `KCLI cluster parameter file` that we've seen involved when bumping into this issue: [Cluster kcli parm. file](https://gist.github.com/larssb/554fc1a79e43cdd366a23547e1613953)

---

I'm especially eager to know whether the actions in `handle_vm_result()` as well as other involved functions will throw breaking errors and log these to stderr so that such can be caught and logged ... so that we can debug with ease.

Looking forward to know what's up.

Thanks.

**Comment by karmab** [comment]
the only ways I can think of the update_ip_alias function not being called would be:
- you scale by creating a vm instead of calling `kcli scale cluster`
- you dont specify cloud_native to true in the parameter file used for scaling

**Comment by larssb** [comment]
Hi @karmab,

Thank you very much for responding.

- We're certainly using the `kcli scale` command
- We're also having `cloud_native: true`

So :-(

**Comment by karmab** [comment]
probably the issue is that we dont capture properly result in threaded mode (which might need a fix), can you try without threaded mode

**Comment by larssb** [comment]
We're now trying this out in our auto scaling flows. Then we'll see.

**Comment by larssb** [comment]
Still watching this ...

**Comment by karmab** [comment]
I feel like closing this because we dont have a reproducer

**Comment by larssb** [comment]
We're still following it. Vacation right now. However, go ahead and let's close it and then I can always re-open if `threaded: false` does not fix it ... if it does and we don't see it then actually `threaded: true` should potentially have a look yes.
