### ISSUE TITLE
[ RFE ] kcli rpms don't have a proper changelog and get refreshed quite often

### ISSUE THREAD

**Issue by ElCoyote27** [karmab/kcli#740]
Hi,

I get my kcli rpms from here:
https://download.copr.fedorainfracloud.org/results/karmab/kcli/epel-8-x86_64
and
https://download.copr.fedorainfracloud.org/results/karmab/kcli/epel-9-x86_64

None of them have a changelog so it's impossible to know what improvements or fixes were merged just by looking at the changelog of the rpms. e.:
```
# ls -lt *rpm
-rw-r--r--. 1 root root 1799032 Nov  8 16:02 kcli-99.0.0.git.202411071453.43ebc7d-0.el8.x86_64.rpm
-rw-r--r--. 1 root root 1798932 Nov  7 11:03 kcli-99.0.0.git.202411061013.2f63d4b-0.el8.x86_64.rpm
-rw-r--r--. 1 root root 1798688 Nov  6 08:41 kcli-99.0.0.git.202411051322.ded28a4-0.el8.x86_64.rpm
-rw-r--r--. 1 root root 1793808 Nov  2 11:21 kcli-99.0.0.git.202411010920.fb028ea-0.el8.x86_64.rpm
-rw-r--r--. 1 root root 1793852 Nov  1 11:06 kcli-99.0.0.git.202410302125.0db54cd-0.el8.x86_64.rpm
-rw-r--r--. 1 root root 1793780 Oct 30 10:43 kcli-99.0.0.git.202410291244.cdc3129-0.el8.x86_64.rpm
-rw-r--r--. 1 root root 1793888 Oct 26 12:09 kcli-99.0.0.git.202410251152.388538e-0.el8.x86_64.rpm
-rw-r--r--. 1 root root 1793568 Oct 24 11:11 kcli-99.0.0.git.202410231325.1f6e394-0.el8.x86_64.rpm
-rw-r--r--. 1 root root 1793436 Oct 23 18:04 kcli-99.0.0.git.202410222003.b9b64b5-0.el8.x86_64.rpm

# rpm -qp --changelog *rpm
#

```
It would be super nice to have changelogs reflecting the commit messages here:
https://github.com/karmab/kcli/commits/main

Thank you

**Comment by karmab** [comment]
https://github.com/karmab/kcli/commit/b31a6d9c023c3bbbf12bd2719ba9c1c65a29200d should fix it
note that you can also use kcli changelog to get changes before updating
