### ISSUE TITLE
Timing out on waiting on CIDR's [GCP] to be assigned should be a breaking error.

### ISSUE THREAD

**Issue by larssb** [karmab/kcli#747]
https://github.com/karmab/kcli/blob/2a1fbed7985ad4e23cd9ab61256992faa4672a2f/kvirt/cluster/k3s/__init__.py#L23

Right now we see

![image](https://github.com/user-attachments/assets/46d44b5e-bd67-4e26-9dcf-9190ff8d6c43)

---

We fence in the call to kcli scale by:

```bash
                if (kcli \
                    --client "${__kcli_client}" \
                    scale kube k3s \
                    --paramfile "${__temp_file}" \
                    -P workers="${__scaleToWorkersCount}" \
                    "${__clustername}"); kcliScaleWorkersErr=$?; (( kcliScaleWorkersErr ));
                then
                    COLOR_STRING "( scaleCluster ) Failed to introduce workers into the ${__clustername} cluster." "ERROR" "bold"
                    COLOR_STRING "The kcli exit code is: ${kcliScaleWorkersErr}" "WARNING" "bold" >&2
                    COLOR_STRING "You'll have to get the ${__clustername} cluster into a healthy state." "WARNING" "bold" >&2
                    exit "${kcliScaleWorkersErr}"
                else
```

Using this `Bash 4.0` try/catch like approach should, in case the kcli scale command throws a breaking error, bring "us" into the `then` branch of the code. But, we never get in there when we see `Timeout waiting for X nodes to have a Pod CIDR assigned`.

I would therefore like this error to be breaking to avoid e.g. other ( more ugly ) workarounds like catching the `Timeout waiting for X nodes to have a Pod CIDR assigned` output ( by re-directing the streams if necessary ) and then conditionally test whether there was a timeout ...

Thanks

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/2a8b6026ff8ad14ff0cc4a9b1d9c733acddf6654

**Comment by larssb** [comment]
Yes it's now a breaking error and we can get to where we want based on that. Thank you very much @karmab
