### ISSUE TITLE
Server is created even if creation fails (not available memory for example)

### ISSUE THREAD

**Issue by morenod** [karmab/kcli#75]
Creating a server from a plan with more memory than available:

$ cat rhel73.yml 
rhel73:
 template: rhel-guest-image-7.3-35.x86_64.qcow2
 memory: 10241024
 numcpus: 2
 disks: 
  - size: 15
 nets:
 - default
 pool: default

$ kcli plan -f rhel73.yml rhel73
Deploying Vms...
Traceback (most recent call last):
  File "/usr/bin/kcli", line 11, in <module>
    load_entry_point('kcli==10.4', 'console_scripts', 'kcli')()
  File "/usr/lib/python2.7/site-packages/kvirt/cli.py", line 1205, in cli
    args.func(args)
  File "/usr/lib/python2.7/site-packages/kvirt/cli.py", line 645, in plan
    config.plan(plan, ansible=ansible, get=get, path=path, autostart=autostart, container=container, noautostart=noautostart, inputfile=inputfile, start=start, stop=stop, delete=delete, delay=delay, topologyfile=topologyfile, scale=scale, overrides=overrides)
  File "/usr/lib/python2.7/site-packages/kvirt/config.py", line 1183, in plan
    result = z.create(name=name, plan=plan, profile=profilename, cpumodel=cpumodel, cpuflags=cpuflags, numcpus=int(numcpus), memory=int(memory), guestid=guestid, pool=pool, template=template, disks=disks, disksize=disksize, diskthin=diskthin, diskinterface=diskinterface, nets=nets, iso=iso, vnc=bool(vnc), cloudinit=bool(cloudinit), reserveip=bool(reserveip), reservedns=bool(reservedns), reservehost=bool(reservehost), start=bool(start), keys=keys, cmds=cmds, ips=ips, netmasks=netmasks, gateway=gateway, dns=dns, domain=domain, nested=nested, tunnel=tunnel, files=files, enableroot=enableroot, overrides=overrides)
  File "/usr/lib/python2.7/site-packages/kvirt/kvm/__init__.py", line 414, in create
    vm.create()
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1062, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2018-01-05T10:05:29.192112Z qemu-system-x86_64: -chardev pty,id=charserial0: char device redirected to /dev/pts/2 (label charserial0)
2018-01-05T10:05:29.213137Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory

$ kcli list
+------------+--------+-----+--------------------------------------+--------+---------+--------+
|    Name    | Status | Ips |                Source                |  Plan  | Profile | Report |
+------------+--------+-----+--------------------------------------+--------+---------+--------+
|   rhel73   |  down  |     | rhel-guest-image-7.3-35.x86_64.qcow2 | rhel73 |  kvirt  |        |
+------------+--------+-----+--------------------------------------+--------+---------+--------+

**Comment by karmab** [comment]
the thing is that it s complicated to really calculate the maximum memory you can assign to a vm, as kvm will overcommit so you can perfectly have a single vm with 10 times your physical memory and running

**Comment by karmab** [comment]
Got fixed at some point, so closing this
![image](https://user-images.githubusercontent.com/1840387/89033380-f4625080-d336-11ea-884a-f7df7a3c2bf3.png)
