### ISSUE TITLE
Error when deploying openshift on proxmox

### ISSUE THREAD

**Issue by easternnl** [karmab/kcli#752]
I got this error when deploying a new openshift cluster. It worked with a previous version, a few weeks ago
```

[xxxx@centos9-kcli .kcli]$ kcli -C proxmox create kube openshift --paramfile shift417.yml $cluster
Deploying on client proxmox
Deploying cluster shift417
Using stable version
Using existing openshift-install found in your PATH
Using installer version 4.17.6
Using image rhcos-417-94-202410090854-0-qemu-x86-64-qcow2
INFO Consuming Install Config from target directory 
INFO Manifests created in: /home/xxxx/.kcli/clusters/shift417/manifests and /home/xxxx/.kcli/clusters/shift417/openshift 
INFO Consuming Common Manifests from target directory 
INFO Consuming OpenShift Install (Manifests) from target directory 
INFO Consuming Master Machines from target directory 
INFO Consuming Openshift Manifests from target directory 
INFO Consuming Worker Machines from target directory 
INFO Ignition-Configs created in: /home/xxxx/.kcli/clusters/shift417 and /home/xxxx/.kcli/clusters/shift417/auth 
Using keepalived virtual_router_id 237
Using 172.x.x.x for api vip....
Deploying bootstrap
Deploying Vms...
Merging ignition data from existing /home/xxxx/.kcli/clusters/shift417/bootstrap.ign for shift417-bootstrap
Waiting for image disk 0 to be resized
shift417-bootstrap not deployed because start failed: QEMU exited with code 1
The following vms failed: shift417-bootstrap
```

on proxmox I got the following details:

```
root@proxmox-z640:/# qm start 118
kvm: -fw_cfg name=opt/com.coreos/config,file=snippets/shift417-bootstrap.ign: can't load snippets/shift417-bootstrap.ign: Failed to open file “snippets/shift417-bootstrap.ign”: No such file or directory
start failed: QEMU exited with code 1
```

however the file exits:
```
root@proxmox-z640:/# find . | grep snippets/shift417-bootstrap.ign
./var/lib/vz/snippets/shift417-bootstrap.ign
root@proxmox-z640:/# 
```

and has content

```
root@proxmox-z640:/# cat ./var/lib/vz/snippets/shift417-bootstrap.ign | head
{
    "ignition": {
        "version": "3.2.0"
    },
    "passwd": {
        "users": [
            {
                "name": "core",
                "sshAuthorizedKeys": [
                    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdMV2cJL9KDVrwrYDSaWp9fgv9E5FIoBa3HW8S4r4joPKqzZkG2TJ9vL0lWdy1gPksavDopVCb3ClQziCUbgypVjZ+wTTpXaVgrS12gROB0Pkakvrp60vyR5WLzcKrgTCCXOkiHoJkovkOgfRYBYd7xgXXm18FLCFAST19hEdNtOmLMouMogiIBQHDGTJQEf+VLG+DanJJxr7/kNw7NzslQ5nn7xd4l4xc0lTEItmyQ/m0VcEIUPAGGt544EWzOBd2Nd71FtMs0nPDhOWDa
root@proxmox-z640:/# 
```

**Comment by easternnl** [comment]
vm config file: 
`#plan=shift417,profile=kvirt,image=rhcos-417-94-202410090854-0-qemu-x86-64-qcow2,kubetype=openshift,kube=shift417,cluster_network=10.132.0.0/14
agent: enabled=1
args: -fw_cfg name=opt/com.coreos/config,file=snippets/shift417-bootstrap.ign
boot: order=virtio0
cores: 4
cpu: host
memory: 8192
meta: creation-qemu=8.1.5,ctime=1732003882
name: shift417-bootstrap
net0: virtio=BC:24:11:8D:0D:CE,bridge=vmbr0
onboot: 1
scsihw: virtio-scsi-pci
smbios1: uuid=76fc0be3-0c4d-4e7e-ad34-f67f944f40f0
virtio0: local-lvm:vm-118-disk-0,size=30G
vmgenid: 3be0e593-a6cf-4ba0-bf59-5e02b55984e1`

**Comment by easternnl** [comment]
The vm will start when using the full path to the snippets:

args: -fw_cfg name=opt/com.coreos/config,file=/var/lib/vz/snippets/shift417-bootstrap.ign

**Comment by karmab** [comment]
fixed by https://github.com/karmab/kcli/commit/866c1bd5b60b525e4995c189afa922aee0e0b049

side note: I think you should be using rhcos openstack image, let me know if you're forcing the qemu in your parameter file, I recommend you dont

**Comment by easternnl** [comment]
I have the following config file, seems not forcing an image:

`cluster: shift417
domain: xxx 
version: stable
tag: '4.17'
ctlplanes: 3
workers: 3
memory: 16384 
numcpus: 4 
network: vmbr0 
api_ip: 172.16.40.162
extra_disks:
- 20
apps:
- local-storage-operator
- odf-operator`

**Comment by karmab** [comment]
indeed, I fixed that now in https://github.com/karmab/kcli/commit/1d36577e8aca2fa8d40c02b7e7b2f6029f9092be
using the openstack image is a "must", the qemu one is slower
