### ISSUE TITLE
kcli bootstrap should create a complete config file

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli#76]
There are lots of options used in the kcli config file, so I think it would be nice if the bootstrap command creates a complete one with all the options commented.

**Comment by karmab** [comment]
thanks... fixed in https://github.com/karmab/kcli/commit/bff43154094ea779dbb6cb0130e349c7d21652a5

**Comment by karmab** [comment]
addressed in https://github.com/karmab/kcli/commit/dc72bbb1bbf0e002e9955264619757e1c64e14a6
where we include default values in the default section of the generated config file for all non empty ones
additionally , the config.yml sample has been commented with all possible options
