### ISSUE TITLE
Use "host-model" as default cpumodel

### ISSUE THREAD

**Issue by e-minguez** [karmab/kcli#80]
The default cpumodel is not compatible with some cpus, so having the "host-model" default will avoid issues as it will use the same as the host running the VM.

https://libvirt.org/formatdomain.html#elementsCPU

**Comment by karmab** [comment]
that's fair but then enabling things like nested virtualization (which is enabled by default) is harder.
plus, you can always set cpu in your profiles or plans with cpumodel: host-model
 
some plans ( rhev for instance) do use host-model this way actually, along with enabled/disabled cpuflags

**Comment by karmab** [comment]
i cam into issues this week with westmere so i decided to indeed default to  host-model.
so, fixed in https://github.com/karmab/kcli/commit/57745e32402d3a5f3bef7b7bc2c15172b89ba6f6
