### ISSUE TITLE
Networking limitations

### ISSUE THREAD

**Issue by NerdsvilleCEO** [karmab/kcli#81]
I was changing up my networking a bit to have a PFSense VM handle the LAN networks and noticed that this breaks cloudinit deployments. It seems that even if I configure a static IP and gateway as well as interface name, it never comes online, but if I use the default network and manually configure it, it works fine. Additionally how can I manage networks using kcli which aren't NAT networks but rather macvtap or isolated.

**Comment by NerdsvilleCEO** [comment]
Update: if I configure the netmask it fixes this issue of it not coming online :+1:  only issue at this point is I don't know how to manage network types other than NAT :)

**Comment by karmab** [comment]
So you can either use kcli network which helps should be self explanatory or include network snippets in your plan.
for instance, the following would create an isolated network without dhcp

```
mynet1:
 type: network
 cidr: 10.0.0.0/24
 dhcp: False
 nat: False
```

also note you can reference existing networks ( regardless of their types ) when creating vms. that includes bridged ones

**Comment by sp3t3rs** [comment]
I couldn't find a method to use macvtap though, am I missing something?
